DiglettsCave_EntranceSouth_hns_MapScripts::
	.byte 0

DiglettsCave_EntranceSouth_EventScript_Scientist::
	msgbox DiglettsCave_EntranceSouth_Text_Scientist, MSGBOX_NPC
	end

DiglettsCave_EntranceSouth_Text_Scientist:
	.string "Astonishing, isn't it?\p"
	.string "A DIGLETT congregation. They lock\n"
	.string "together like this perhaps twice\l"
	.string "in a century.\p"
	.string "Nobody knows what calls them up.\p"
	.string "We could clear them in an hour.\n"
	.string "We are not going to.\p"
	.string "You'll have to go the long way\n"
	.string "round, I'm afraid.$"
