// Kismet: modern egg moves ported from pokemonHnS.
//
// Generated by .claude/eggmove_emit.py - do not hand-edit; re-run
// the script. Sparse: only species the fork retunes appear here,
// everything else falls through to gSpeciesInfo[].eggMoveLearnset.
//
// Six fork lists are deliberately absent - see the script's
// docstring. Four are copy-paste leftovers from species swaps;
// Drapion's and Gallade's could never fire, as nothing hatches
// as either.

#include "constants/moves.h"

#if P_FAMILY_BULBASAUR
static const u16 sBulbasaurEggMoveLearnset_Kismet[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_INGRAIN,
    MOVE_SKULL_BASH,
    MOVE_SAFEGUARD,
    MOVE_CHARM,
    MOVE_PETAL_DANCE,
    MOVE_SLUDGE,
    MOVE_NATURE_POWER,
    MOVE_MAGICAL_LEAF,
    MOVE_GRASS_WHISTLE,
    MOVE_EARTH_POWER,
    MOVE_WEATHER_BALL,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHARMANDER
static const u16 sCharmanderEggMoveLearnset_Kismet[] = {
    MOVE_BELLY_DRUM,
    MOVE_DRAGON_PULSE,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_BITE,
    MOVE_OUTRAGE,
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_METAL_CLAW,
    MOVE_BEAT_UP,
    MOVE_SWORDS_DANCE,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SQUIRTLE
static const u16 sSquirtleEggMoveLearnset_Kismet[] = {
    MOVE_MIRROR_COAT,
    MOVE_DRAGON_PULSE,
    MOVE_DARK_PULSE,
    MOVE_FAKE_OUT,
    MOVE_MUDDY_WATER,
    MOVE_HAZE,
    MOVE_MIST,
    MOVE_FORESIGHT,
    MOVE_FLAIL,
    MOVE_REFRESH,
    MOVE_MUD_SPORT,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PIDGEY
static const u16 sPidgeyEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_UPROAR,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_STEEL_WING,
    MOVE_AIR_SLASH,
    MOVE_AIR_CUTTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RATTATA
static const u16 sRattataEggMoveLearnset_Kismet[] = {
    MOVE_SCREECH,
    MOVE_FLAME_WHEEL,
    MOVE_FURY_SWIPES,
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_REVERSAL,
    MOVE_UPROAR,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPEAROW
static const u16 sSpearowEggMoveLearnset_Kismet[] = {
    MOVE_FAINT_ATTACK,
    MOVE_UPROAR,
    MOVE_WHIRLWIND,
    MOVE_FALSE_SWIPE,
    MOVE_SCARY_FACE,
    MOVE_QUICK_ATTACK,
    MOVE_TRI_ATTACK,
    MOVE_ASTONISH,
    MOVE_SKY_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EKANS
static const u16 sEkansEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_DISABLE,
    MOVE_POISON_TAIL,
    MOVE_SCARY_FACE,
    MOVE_SLAM,
    MOVE_SPITE,
    MOVE_BEAT_UP,
    MOVE_POISON_FANG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PIKACHU
#if P_GEN_2_CROSS_EVOS
static const u16 sPichuEggMoveLearnset_Kismet[] = {
    MOVE_REVERSAL,
    MOVE_FAKE_OUT,
    MOVE_FLAIL,
    MOVE_THUNDER_PUNCH,
    MOVE_TICKLE,
    MOVE_BIDE,
    MOVE_PRESENT,
    MOVE_ENCORE,
    MOVE_DOUBLE_SLAP,
    MOVE_WISH,
    MOVE_CHARGE,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_SANDSHREW
static const u16 sSandshrewEggMoveLearnset_Kismet[] = {
    MOVE_FLAIL,
    MOVE_MUD_SHOT,
    MOVE_SAFEGUARD,
    MOVE_COUNTER,
    MOVE_NEEDLE_ARM,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_METAL_CLAW,
    MOVE_SWORDS_DANCE,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NIDORAN
static const u16 sNidoranFEggMoveLearnset_Kismet[] = {
    MOVE_SUPERSONIC,
    MOVE_SKULL_BASH,
    MOVE_DISABLE,
    MOVE_TAKE_DOWN,
    MOVE_FOCUS_ENERGY,
    MOVE_CHARM,
    MOVE_COUNTER,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

static const u16 sNidoranMEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_SKULL_BASH,
    MOVE_DISABLE,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CLEFAIRY
#if P_GEN_2_CROSS_EVOS
static const u16 sCleffaEggMoveLearnset_Kismet[] = {
    MOVE_PRESENT,
    MOVE_AROMATHERAPY,
    MOVE_COVET,
    MOVE_METRONOME,
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_SPLASH,
    MOVE_MIMIC,
    MOVE_WISH,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_VULPIX
static const u16 sVulpixEggMoveLearnset_Kismet[] = {
    MOVE_FAINT_ATTACK,
    MOVE_DARK_PULSE,
    MOVE_EXTRASENSORY,
    MOVE_HYPNOSIS,
    MOVE_FLAIL,
    MOVE_SPITE,
    MOVE_DISABLE,
    MOVE_HOWL,
    MOVE_PSYCH_UP,
    MOVE_LICK,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_JIGGLYPUFF
#if P_GEN_2_CROSS_EVOS
static const u16 sIgglybuffEggMoveLearnset_Kismet[] = {
    MOVE_PERISH_SONG,
    MOVE_COVET,
    MOVE_PRESENT,
    MOVE_FAINT_ATTACK,
    MOVE_WISH,
    MOVE_FAKE_TEARS,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_ZUBAT
static const u16 sZubatEggMoveLearnset_Kismet[] = {
    MOVE_QUICK_ATTACK,
    MOVE_PURSUIT,
    MOVE_FAINT_ATTACK,
    MOVE_SHADOW_SNEAK,
    MOVE_GUST,
    MOVE_CRUNCH,
    MOVE_HYPNOSIS,
    MOVE_WHIRLWIND,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ODDISH
static const u16 sOddishEggMoveLearnset_Kismet[] = {
    MOVE_SWORDS_DANCE,
    MOVE_TEETER_DANCE,
    MOVE_TICKLE,
    MOVE_RAZOR_LEAF,
    MOVE_FLAIL,
    MOVE_SYNTHESIS,
    MOVE_CHARM,
    MOVE_INGRAIN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PARAS
static const u16 sParasEggMoveLearnset_Kismet[] = {
    MOVE_FALSE_SWIPE,
    MOVE_AGILITY,
    MOVE_METAL_CLAW,
    MOVE_SCREECH,
    MOVE_LEECH_SEED,
    MOVE_COUNTER,
    MOVE_PSYBEAM,
    MOVE_FLAIL,
    MOVE_SWEET_SCENT,
    MOVE_LIGHT_SCREEN,
    MOVE_PURSUIT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VENONAT
static const u16 sVenonatEggMoveLearnset_Kismet[] = {
    MOVE_BATON_PASS,
    MOVE_AGILITY,
    MOVE_SCREECH,
    MOVE_GIGA_DRAIN,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DIGLETT
static const u16 sDiglettEggMoveLearnset_Kismet[] = {
    MOVE_FAINT_ATTACK,
    MOVE_SCREECH,
    MOVE_ANCIENT_POWER,
    MOVE_REVERSAL,
    MOVE_PURSUIT,
    MOVE_BEAT_UP,
    MOVE_UPROAR,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MEOWTH
static const u16 sMeowthEggMoveLearnset_Kismet[] = {
    MOVE_SPITE,
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_ODOR_SLEUTH,
    MOVE_TAIL_WHIP,
    MOVE_HYPNOSIS,
    MOVE_SHADOW_SNEAK,
    MOVE_AMNESIA,
    MOVE_PSYCH_UP,
    MOVE_ASSIST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PSYDUCK
static const u16 sPsyduckEggMoveLearnset_Kismet[] = {
    MOVE_HYPNOSIS,
    MOVE_CONFUSE_RAY,
    MOVE_ENCORE,
    MOVE_YAWN,
    MOVE_PSYBEAM,
    MOVE_FORESIGHT,
    MOVE_LIGHT_SCREEN,
    MOVE_FUTURE_SIGHT,
    MOVE_PSYCHIC,
    MOVE_CROSS_CHOP,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MANKEY
static const u16 sMankeyEggMoveLearnset_Kismet[] = {
    MOVE_ROCK_SLIDE,
    MOVE_ENCORE,
    MOVE_FORESIGHT,
    MOVE_MEDITATE,
    MOVE_COUNTER,
    MOVE_REVERSAL,
    MOVE_BEAT_UP,
    MOVE_REVENGE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GROWLITHE
static const u16 sGrowlitheEggMoveLearnset_Kismet[] = {
    MOVE_BODY_SLAM,
    MOVE_SAFEGUARD,
    MOVE_DRAGON_PULSE,
    MOVE_DOUBLE_EDGE,
    MOVE_CRUNCH,
    MOVE_THRASH,
    MOVE_FIRE_SPIN,
    MOVE_HOWL,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_POLIWAG
static const u16 sPoliwagEggMoveLearnset_Kismet[] = {
    MOVE_MIST,
    MOVE_ENCORE,
    MOVE_ENDEAVOR,
    MOVE_SPLASH,
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_MIND_READER,
    MOVE_WATER_SPORT,
    MOVE_ICE_BALL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ABRA
static const u16 sAbraEggMoveLearnset_Kismet[] = {
    MOVE_ENCORE,
    MOVE_BARRIER,
    MOVE_TRI_ATTACK,
    MOVE_KNOCK_OFF,
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MACHOP
static const u16 sMachopEggMoveLearnset_Kismet[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_THUNDER_PUNCH,
    MOVE_MEDITATE,
    MOVE_ROLLING_KICK,
    MOVE_ENCORE,
    MOVE_SMELLING_SALTS,
    MOVE_COUNTER,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BELLSPROUT
static const u16 sBellsproutEggMoveLearnset_Kismet[] = {
    MOVE_SWORDS_DANCE,
    MOVE_ENCORE,
    MOVE_REFLECT,
    MOVE_SYNTHESIS,
    MOVE_LEECH_LIFE,
    MOVE_INGRAIN,
    MOVE_WEATHER_BALL,
    MOVE_MAGICAL_LEAF,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TENTACOOL
static const u16 sTentacoolEggMoveLearnset_Kismet[] = {
    MOVE_AURORA_BEAM,
    MOVE_MIRROR_COAT,
    MOVE_KNOCK_OFF,
    MOVE_MUDDY_WATER,
    MOVE_RAPID_SPIN,
    MOVE_HAZE,
    MOVE_SAFEGUARD,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GEODUDE
static const u16 sGeodudeEggMoveLearnset_Kismet[] = {
    MOVE_MEGA_PUNCH,
    MOVE_FLAIL,
    MOVE_CURSE,
    MOVE_ROCK_SLIDE,
    MOVE_BLOCK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PONYTA
static const u16 sPonytaEggMoveLearnset_Kismet[] = {
    MOVE_FLAME_WHEEL,
    MOVE_SCORCHING_SANDS,
    MOVE_THRASH,
    MOVE_HORN_DRILL,
    MOVE_DOUBLE_KICK,
    MOVE_HYPNOSIS,
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLOWPOKE
static const u16 sSlowpokeEggMoveLearnset_Kismet[] = {
    MOVE_SAFEGUARD,
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_STOMP,
    MOVE_BLOCK,
    MOVE_MUD_SPORT,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FARFETCHD
static const u16 sFarfetchdEggMoveLearnset_Kismet[] = {
    MOVE_STEEL_WING,
    MOVE_FORESIGHT,
    MOVE_COVET,
    MOVE_LEAF_BLADE,
    MOVE_MUD_SLAP,
    MOVE_FAINT_ATTACK,
    MOVE_MIRROR_MOVE,
    MOVE_GUST,
    MOVE_QUICK_ATTACK,
    MOVE_FLAIL,
    MOVE_FEATHER_DANCE,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DODUO
static const u16 sDoduoEggMoveLearnset_Kismet[] = {
    MOVE_QUICK_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_MIRROR_MOVE,
    MOVE_HAZE,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEEL
static const u16 sSeelEggMoveLearnset_Kismet[] = {
    MOVE_LICK,
    MOVE_PERISH_SONG,
    MOVE_DISABLE,
    MOVE_SIGNAL_BEAM,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_HORN_DRILL,
    MOVE_SLAM,
    MOVE_SAFEGUARD,
    MOVE_ENCORE,
    MOVE_FAKE_OUT,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GRIMER
static const u16 sGrimerEggMoveLearnset_Kismet[] = {
    MOVE_HAZE,
    MOVE_MEAN_LOOK,
    MOVE_SHADOW_SNEAK,
    MOVE_LICK,
    MOVE_IMPRISON,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_CURSE,
    MOVE_SHADOW_PUNCH,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHELLDER
static const u16 sShellderEggMoveLearnset_Kismet[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_TAKE_DOWN,
    MOVE_MUD_SHOT,
    MOVE_BARRIER,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_BLAST,
    MOVE_SCREECH,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GASTLY
static const u16 sGastlyEggMoveLearnset_Kismet[] = {
    MOVE_PSYWAVE,
    MOVE_PERISH_SONG,
    MOVE_HAZE,
    MOVE_ASTONISH,
    MOVE_DISABLE,
    MOVE_SHADOW_SNEAK,
    MOVE_WILL_O_WISP,
    MOVE_GRUDGE,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ONIX
static const u16 sOnixEggMoveLearnset_Kismet[] = {
    MOVE_ROCK_SLIDE,
    MOVE_DEFENSE_CURL,
    MOVE_ROCK_BLAST,
    MOVE_ROLLOUT,
    MOVE_FLAIL,
    MOVE_EXPLOSION,
    MOVE_BLOCK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DROWZEE
static const u16 sDrowzeeEggMoveLearnset_Kismet[] = {
    MOVE_BARRIER,
    MOVE_PSYCHO_CUT,
    MOVE_ASSIST,
    MOVE_FLATTER,
    MOVE_SHADOW_SNEAK,
    MOVE_ROLE_PLAY,
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KRABBY
static const u16 sKrabbyEggMoveLearnset_Kismet[] = {
    MOVE_DIG,
    MOVE_AGILITY,
    MOVE_ANCIENT_POWER,
    MOVE_TICKLE,
    MOVE_HAZE,
    MOVE_AMNESIA,
    MOVE_FLAIL,
    MOVE_SLAM,
    MOVE_KNOCK_OFF,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EXEGGCUTE
static const u16 sExeggcuteEggMoveLearnset_Kismet[] = {
    MOVE_SYNTHESIS,
    MOVE_MOONLIGHT,
    MOVE_REFLECT,
    MOVE_NATURE_POWER,
    MOVE_ANCIENT_POWER,
    MOVE_PSYCH_UP,
    MOVE_INGRAIN,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CUBONE
static const u16 sCuboneEggMoveLearnset_Kismet[] = {
    MOVE_ROCK_SLIDE,
    MOVE_ANCIENT_POWER,
    MOVE_BELLY_DRUM,
    MOVE_DETECT,
    MOVE_DOUBLE_KICK,
    MOVE_SCREECH,
    MOVE_SKULL_BASH,
    MOVE_PERISH_SONG,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HITMONS
#if P_GEN_2_CROSS_EVOS
static const u16 sTyrogueEggMoveLearnset_Kismet[] = {
    MOVE_RAPID_SPIN,
    MOVE_COUNTER,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_LICKITUNG
static const u16 sLickitungEggMoveLearnset_Kismet[] = {
    MOVE_BELLY_DRUM,
    MOVE_MAGNITUDE,
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_AMNESIA,
    MOVE_MUDDY_WATER,
    MOVE_SMELLING_SALTS,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KOFFING
static const u16 sKoffingEggMoveLearnset_Kismet[] = {
    MOVE_SCREECH,
    MOVE_PSYWAVE,
    MOVE_PSYBEAM,
    MOVE_CURSE,
    MOVE_GRUDGE,
    MOVE_SPITE,
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RHYHORN
static const u16 sRhyhornEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_REVERSAL,
    MOVE_SKULL_BASH,
    MOVE_ROCK_SLIDE,
    MOVE_FLAIL,
    MOVE_COUNTER,
    MOVE_MAGNITUDE,
    MOVE_SWORDS_DANCE,
    MOVE_CURSE,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHANSEY
static const u16 sChanseyEggMoveLearnset_Kismet[] = {
    MOVE_PRESENT,
    MOVE_COUNTER,
    MOVE_HELPING_HAND,
    MOVE_METRONOME,
    MOVE_HEAL_BELL,
    MOVE_AROMATHERAPY,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TANGELA
static const u16 sTangelaEggMoveLearnset_Kismet[] = {
    MOVE_FLAIL,
    MOVE_CONFUSION,
    MOVE_MEGA_DRAIN,
    MOVE_REFLECT,
    MOVE_AMNESIA,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KANGASKHAN
static const u16 sKangaskhanEggMoveLearnset_Kismet[] = {
    MOVE_STOMP,
    MOVE_FORESIGHT,
    MOVE_FOCUS_ENERGY,
    MOVE_DOUBLE_EDGE,
    MOVE_ENDEAVOR,
    MOVE_SAFEGUARD,
    MOVE_DISABLE,
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_SUBSTITUTE,
    MOVE_SUPERPOWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HORSEA
static const u16 sHorseaEggMoveLearnset_Kismet[] = {
    MOVE_FLAIL,
    MOVE_AURORA_BEAM,
    MOVE_MUDDY_WATER,
    MOVE_SIGNAL_BEAM,
    MOVE_OCTAZOOKA,
    MOVE_DISABLE,
    MOVE_SPLASH,
    MOVE_DRAGON_RAGE,
    MOVE_DRAGON_BREATH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GOLDEEN
static const u16 sGoldeenEggMoveLearnset_Kismet[] = {
    MOVE_PSYBEAM,
    MOVE_HAZE,
    MOVE_BODY_SLAM,
    MOVE_MUD_SLAP,
    MOVE_HYDRO_PUMP,
    MOVE_SLEEP_TALK,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MR_MIME
static const u16 sMrMimeEggMoveLearnset_Kismet[] = {
    MOVE_CHARM,
    MOVE_CONFUSE_RAY,
    MOVE_TEETER_DANCE,
    MOVE_FUTURE_SIGHT,
    MOVE_HYPNOSIS,
    MOVE_MIMIC,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SCYTHER
static const u16 sScytherEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_BUG_BUZZ,
    MOVE_SAFEGUARD,
    MOVE_BATON_PASS,
    MOVE_RAZOR_WIND,
    MOVE_REVERSAL,
    MOVE_LIGHT_SCREEN,
    MOVE_ENDURE,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_JYNX
#if P_GEN_2_CROSS_EVOS
static const u16 sSmoochumEggMoveLearnset_Kismet[] = {
    MOVE_MEDITATE,
    MOVE_PSYCH_UP,
    MOVE_BODY_SLAM,
    MOVE_FAKE_OUT,
    MOVE_WISH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_ELECTABUZZ
#if P_GEN_2_CROSS_EVOS
static const u16 sElekidEggMoveLearnset_Kismet[] = {
    MOVE_KARATE_CHOP,
    MOVE_BARRIER,
    MOVE_ROLLING_KICK,
    MOVE_DYNAMIC_PUNCH,
    MOVE_MEDITATE,
    MOVE_CROSS_CHOP,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_MAGMAR
#if P_GEN_2_CROSS_EVOS
static const u16 sMagbyEggMoveLearnset_Kismet[] = {
    MOVE_KARATE_CHOP,
    MOVE_DYNAMIC_PUNCH,
    MOVE_BELLY_DRUM,
    MOVE_MEGA_PUNCH,
    MOVE_BARRIER,
    MOVE_SCREECH,
    MOVE_CROSS_CHOP,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_PINSIR
static const u16 sPinsirEggMoveLearnset_Kismet[] = {
    MOVE_FURY_ATTACK,
    MOVE_QUICK_ATTACK,
    MOVE_BIND,
    MOVE_FLAIL,
    MOVE_FALSE_SWIPE,
    MOVE_FAINT_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LAPRAS
static const u16 sLaprasEggMoveLearnset_Kismet[] = {
    MOVE_FORESIGHT,
    MOVE_DRAGON_PULSE,
    MOVE_ANCIENT_POWER,
    MOVE_FISSURE,
    MOVE_WHIRLPOOL,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_REFRESH,
    MOVE_DRAGON_DANCE,
    MOVE_CURSE,
    MOVE_SLEEP_TALK,
    MOVE_HORN_DRILL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EEVEE
static const u16 sEeveeEggMoveLearnset_Kismet[] = {
    MOVE_CHARM,
    MOVE_COVET,
    MOVE_DETECT,
    MOVE_YAWN,
    MOVE_FLAIL,
    MOVE_ENDURE,
    MOVE_CURSE,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_OMANYTE
static const u16 sOmanyteEggMoveLearnset_Kismet[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_MUDDY_WATER,
    MOVE_AURORA_BEAM,
    MOVE_SLAM,
    MOVE_SUPERSONIC,
    MOVE_HAZE,
    MOVE_ROCK_SLIDE,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KABUTO
static const u16 sKabutoEggMoveLearnset_Kismet[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_AURORA_BEAM,
    MOVE_ICY_WIND,
    MOVE_SCREECH,
    MOVE_RAPID_SPIN,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_KNOCK_OFF,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AERODACTYL
static const u16 sAerodactylEggMoveLearnset_Kismet[] = {
    MOVE_WHIRLWIND,
    MOVE_PURSUIT,
    MOVE_FORESIGHT,
    MOVE_STEEL_WING,
    MOVE_DRAGON_BREATH,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNORLAX
static const u16 sSnorlaxEggMoveLearnset_Kismet[] = {
    MOVE_WHIRLWIND,
    MOVE_COUNTER,
    MOVE_LICK,
    MOVE_PURSUIT,
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_SUBSTITUTE,
    MOVE_FOCUS_BLAST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DRATINI
static const u16 sDratiniEggMoveLearnset_Kismet[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_DRAGON_PULSE,
    MOVE_EXTREME_SPEED,
    MOVE_MIST,
    MOVE_HAZE,
    MOVE_SUPERSONIC,
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHIKORITA
static const u16 sChikoritaEggMoveLearnset_Kismet[] = {
    MOVE_VINE_WHIP,
    MOVE_AROMATHERAPY,
    MOVE_BODY_SLAM,
    MOVE_NATURE_POWER,
    MOVE_LEECH_SEED,
    MOVE_COUNTER,
    MOVE_ANCIENT_POWER,
    MOVE_FLAIL,
    MOVE_SAFEGUARD,
    MOVE_NATURE_POWER,
    MOVE_INGRAIN,
    MOVE_GRASS_WHISTLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CYNDAQUIL
static const u16 sCyndaquilEggMoveLearnset_Kismet[] = {
    MOVE_FURY_SWIPES,
    MOVE_DOUBLE_EDGE,
    MOVE_DOUBLE_KICK,
    MOVE_EXTRASENSORY,
    MOVE_QUICK_ATTACK,
    MOVE_REVERSAL,
    MOVE_THRASH,
    MOVE_FORESIGHT,
    MOVE_COVET,
    MOVE_HOWL,
    MOVE_CRUSH_CLAW,
    MOVE_PLAY_ROUGH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TOTODILE
static const u16 sTotodileEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_THRASH,
    MOVE_HYDRO_PUMP,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_MUD_SPORT,
    MOVE_WATER_SPORT,
    MOVE_DRAGON_DANCE,
    MOVE_ICE_PUNCH,
    MOVE_METAL_CLAW,
    MOVE_DRAGON_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SENTRET
static const u16 sSentretEggMoveLearnset_Kismet[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_CHARM,
    MOVE_COVET,
    MOVE_FOCUS_ENERGY,
    MOVE_REVERSAL,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_ASSIST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOOTHOOT
static const u16 sHoothootEggMoveLearnset_Kismet[] = {
    MOVE_MIRROR_MOVE,
    MOVE_AGILITY,
    MOVE_SUPERSONIC,
    MOVE_OMINOUS_WIND,
    MOVE_FAINT_ATTACK,
    MOVE_NIGHT_SHADE,
    MOVE_BIDE,
    MOVE_WING_ATTACK,
    MOVE_SHADOW_SNEAK,
    MOVE_WHIRLWIND,
    MOVE_SKY_ATTACK,
    MOVE_FEATHER_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LEDYBA
static const u16 sLedybaEggMoveLearnset_Kismet[] = {
    MOVE_PSYBEAM,
    MOVE_BUG_BUZZ,
    MOVE_BIDE,
    MOVE_ENCORE,
    MOVE_KNOCK_OFF,
    MOVE_SCREECH,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPINARAK
static const u16 sSpinarakEggMoveLearnset_Kismet[] = {
    MOVE_PSYBEAM,
    MOVE_DISABLE,
    MOVE_SONIC_BOOM,
    MOVE_BATON_PASS,
    MOVE_PURSUIT,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHINCHOU
static const u16 sChinchouEggMoveLearnset_Kismet[] = {
    MOVE_FLAIL,
    MOVE_SCREECH,
    MOVE_AGILITY,
    MOVE_PSYBEAM,
    MOVE_WHIRLPOOL,
    MOVE_AMNESIA,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TOGEPI
static const u16 sTogepiEggMoveLearnset_Kismet[] = {
    MOVE_PRESENT,
    MOVE_EXTRASENSORY,
    MOVE_MIRROR_MOVE,
    MOVE_PECK,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_SUBSTITUTE,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NATU
static const u16 sNatuEggMoveLearnset_Kismet[] = {
    MOVE_HAZE,
    MOVE_DRILL_PECK,
    MOVE_QUICK_ATTACK,
    MOVE_FAINT_ATTACK,
    MOVE_STEEL_WING,
    MOVE_PSYCH_UP,
    MOVE_SHADOW_SNEAK,
    MOVE_FEATHER_DANCE,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MAREEP
static const u16 sMareepEggMoveLearnset_Kismet[] = {
    MOVE_TAKE_DOWN,
    MOVE_BODY_SLAM,
    MOVE_FLATTER,
    MOVE_SAND_ATTACK,
    MOVE_SAFEGUARD,
    MOVE_SCREECH,
    MOVE_REFLECT,
    MOVE_ODOR_SLEUTH,
    MOVE_CHARGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MARILL
static const u16 sMarillEggMoveLearnset_Kismet[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_PRESENT,
    MOVE_AMNESIA,
    MOVE_FUTURE_SIGHT,
    MOVE_BELLY_DRUM,
    MOVE_PERISH_SONG,
    MOVE_SUPERSONIC,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SUDOWOODO
static const u16 sSudowoodoEggMoveLearnset_Kismet[] = {
    MOVE_DEFENSE_CURL,
    MOVE_HARDEN,
    MOVE_HEADBUTT,
    MOVE_FLAIL,
    MOVE_ROLLOUT,
    MOVE_SAND_TOMB,
    MOVE_SELF_DESTRUCT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOPPIP
static const u16 sHoppipEggMoveLearnset_Kismet[] = {
    MOVE_CONFUSION,
    MOVE_ENCORE,
    MOVE_DOUBLE_EDGE,
    MOVE_REFLECT,
    MOVE_AMNESIA,
    MOVE_AROMATHERAPY,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AIPOM
static const u16 sAipomEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_SCREECH,
    MOVE_PURSUIT,
    MOVE_AGILITY,
    MOVE_SPITE,
    MOVE_BOUNCE,
    MOVE_SLAM,
    MOVE_SHADOW_SNEAK,
    MOVE_FAKE_OUT,
    MOVE_DOUBLE_SLAP,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SUNKERN
static const u16 sSunkernEggMoveLearnset_Kismet[] = {
    MOVE_GRASS_WHISTLE,
    MOVE_ENCORE,
    MOVE_INGRAIN,
    MOVE_SUNNY_DAY,
    MOVE_EMBER,
    MOVE_FIRE_SPIN,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_CURSE,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_YANMA
static const u16 sYanmaEggMoveLearnset_Kismet[] = {
    MOVE_WHIRLWIND,
    MOVE_FAINT_ATTACK,
    MOVE_PURSUIT,
    MOVE_REVERSAL,
    MOVE_LEECH_LIFE,
    MOVE_SIGNAL_BEAM,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WOOPER
static const u16 sWooperEggMoveLearnset_Kismet[] = {
    MOVE_BODY_SLAM,
    MOVE_COUNTER,
    MOVE_DOUBLE_KICK,
    MOVE_ENCORE,
    MOVE_RECOVER,
    MOVE_ANCIENT_POWER,
    MOVE_SAFEGUARD,
    MOVE_CURSE,
    MOVE_MUD_SPORT,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MURKROW
static const u16 sMurkrowEggMoveLearnset_Kismet[] = {
    MOVE_WHIRLWIND,
    MOVE_DRILL_PECK,
    MOVE_MIRROR_MOVE,
    MOVE_WING_ATTACK,
    MOVE_PAY_DAY,
    MOVE_HEAT_WAVE,
    MOVE_SKY_ATTACK,
    MOVE_CONFUSE_RAY,
    MOVE_FEATHER_DANCE,
    MOVE_SHADOW_SNEAK,
    MOVE_PERISH_SONG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MISDREAVUS
static const u16 sMisdreavusEggMoveLearnset_Kismet[] = {
    MOVE_SCREECH,
    MOVE_CURSE,
    MOVE_MEMENTO,
    MOVE_SHADOW_SNEAK,
    MOVE_SPITE,
    MOVE_DESTINY_BOND,
    MOVE_PSYCH_UP,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GIRAFARIG
static const u16 sGirafarigEggMoveLearnset_Kismet[] = {
    MOVE_TAKE_DOWN,
    MOVE_DOUBLE_KICK,
    MOVE_RAZOR_WIND,
    MOVE_AMNESIA,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_BEAT_UP,
    MOVE_PSYCH_UP,
    MOVE_WISH,
    MOVE_MAGIC_COAT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PINECO
static const u16 sPinecoEggMoveLearnset_Kismet[] = {
    MOVE_REFLECT,
    MOVE_PIN_MISSILE,
    MOVE_DOUBLE_EDGE,
    MOVE_REVENGE,
    MOVE_ROCK_THROW,
    MOVE_FLAIL,
    MOVE_SWIFT,
    MOVE_COUNTER,
    MOVE_SAND_TOMB,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DUNSPARCE
static const u16 sDunsparceEggMoveLearnset_Kismet[] = {
    MOVE_BIDE,
    MOVE_AGILITY,
    MOVE_MAGIC_COAT,
    MOVE_SNORE,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_BITE,
    MOVE_HEADBUTT,
    MOVE_ASTONISH,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GLIGAR
static const u16 sGligarEggMoveLearnset_Kismet[] = {
    MOVE_METAL_CLAW,
    MOVE_WING_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_COUNTER,
    MOVE_AGILITY,
    MOVE_BATON_PASS,
    MOVE_DOUBLE_EDGE,
    MOVE_SAND_TOMB,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNUBBULL
static const u16 sSnubbullEggMoveLearnset_Kismet[] = {
    MOVE_METRONOME,
    MOVE_FAINT_ATTACK,
    MOVE_REFLECT,
    MOVE_PRESENT,
    MOVE_CRUNCH,
    MOVE_HEAL_BELL,
    MOVE_SNORE,
    MOVE_SMELLING_SALTS,
    MOVE_KNOCK_OFF,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_QWILFISH
static const u16 sQwilfishEggMoveLearnset_Kismet[] = {
    MOVE_FLAIL,
    MOVE_SIGNAL_BEAM,
    MOVE_HAZE,
    MOVE_BUBBLE_BEAM,
    MOVE_SUPERSONIC,
    MOVE_ASTONISH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHUCKLE
static const u16 sShuckleEggMoveLearnset_Kismet[] = {
    MOVE_SWEET_SCENT,
    MOVE_MUD_SLAP,
    MOVE_KNOCK_OFF,
    MOVE_SAND_TOMB,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HERACROSS
static const u16 sHeracrossEggMoveLearnset_Kismet[] = {
    MOVE_HARDEN,
    MOVE_BIDE,
    MOVE_DOUBLE_EDGE,
    MOVE_PURSUIT,
    MOVE_REVENGE,
    MOVE_FLAIL,
    MOVE_FALSE_SWIPE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNEASEL
static const u16 sSneaselEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_ASSIST,
    MOVE_ICE_PUNCH,
    MOVE_PURSUIT,
    MOVE_SPITE,
    MOVE_FORESIGHT,
    MOVE_REFLECT,
    MOVE_BITE,
    MOVE_LOW_KICK,
    MOVE_CRUSH_CLAW,
    MOVE_SHADOW_SNEAK,
    MOVE_FAKE_OUT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TEDDIURSA
static const u16 sTeddiursaEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_PLAY_ROUGH,
    MOVE_BELLY_DRUM,
    MOVE_CROSS_CHOP,
    MOVE_TAKE_DOWN,
    MOVE_DOUBLE_EDGE,
    MOVE_SEISMIC_TOSS,
    MOVE_COUNTER,
    MOVE_METAL_CLAW,
    MOVE_FAKE_TEARS,
    MOVE_YAWN,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLUGMA
static const u16 sSlugmaEggMoveLearnset_Kismet[] = {
    MOVE_ACID_ARMOR,
    MOVE_CURSE,
    MOVE_SMOKESCREEN,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_EARTH_POWER,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SWINUB
static const u16 sSwinubEggMoveLearnset_Kismet[] = {
    MOVE_TAKE_DOWN,
    MOVE_BITE,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_BODY_SLAM,
    MOVE_ROCK_SLIDE,
    MOVE_ANCIENT_POWER,
    MOVE_MUD_SHOT,
    MOVE_ICICLE_SPEAR,
    MOVE_DOUBLE_EDGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CORSOLA
static const u16 sCorsolaEggMoveLearnset_Kismet[] = {
    MOVE_ROCK_SLIDE,
    MOVE_CURSE,
    MOVE_NATURE_POWER,
    MOVE_SCREECH,
    MOVE_MIST,
    MOVE_AMNESIA,
    MOVE_BARRIER,
    MOVE_INGRAIN,
    MOVE_CONFUSE_RAY,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_REMORAID
static const u16 sRemoraidEggMoveLearnset_Kismet[] = {
    MOVE_AURORA_BEAM,
    MOVE_OCTAZOOKA,
    MOVE_SUPERSONIC,
    MOVE_HAZE,
    MOVE_SCREECH,
    MOVE_SNORE,
    MOVE_WATER_SPOUT,
    MOVE_THUNDER_WAVE,
    MOVE_ROCK_BLAST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DELIBIRD
static const u16 sDelibirdEggMoveLearnset_Kismet[] = {
    MOVE_AURORA_BEAM,
    MOVE_FAKE_OUT,
    MOVE_ICE_PUNCH,
    MOVE_QUICK_ATTACK,
    MOVE_EXTRASENSORY,
    MOVE_FUTURE_SIGHT,
    MOVE_SPLASH,
    MOVE_RAPID_SPIN,
    MOVE_ICE_BALL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MANTINE
static const u16 sMantineEggMoveLearnset_Kismet[] = {
    MOVE_TWISTER,
    MOVE_MIRROR_COAT,
    MOVE_SPLASH,
    MOVE_HYDRO_PUMP,
    MOVE_HAZE,
    MOVE_SLAM,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKARMORY
static const u16 sSkarmoryEggMoveLearnset_Kismet[] = {
    MOVE_DRILL_PECK,
    MOVE_PURSUIT,
    MOVE_WHIRLWIND,
    MOVE_SKY_ATTACK,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOUNDOUR
static const u16 sHoundourEggMoveLearnset_Kismet[] = {
    MOVE_FIRE_SPIN,
    MOVE_RAGE,
    MOVE_PURSUIT,
    MOVE_COUNTER,
    MOVE_SPITE,
    MOVE_REVERSAL,
    MOVE_SHADOW_SNEAK,
    MOVE_BEAT_UP,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PHANPY
static const u16 sPhanpyEggMoveLearnset_Kismet[] = {
    MOVE_FOCUS_ENERGY,
    MOVE_ENDEAVOR,
    MOVE_PLAY_ROUGH,
    MOVE_BODY_SLAM,
    MOVE_ANCIENT_POWER,
    MOVE_SNORE,
    MOVE_COUNTER,
    MOVE_FISSURE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_STANTLER
static const u16 sStantlerEggMoveLearnset_Kismet[] = {
    MOVE_SPITE,
    MOVE_DISABLE,
    MOVE_BITE,
    MOVE_SWAGGER,
    MOVE_PSYCH_UP,
    MOVE_MEGAHORN,
    MOVE_DOUBLE_KICK,
    MOVE_THRASH,
    MOVE_EXTRASENSORY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MILTANK
static const u16 sMiltankEggMoveLearnset_Kismet[] = {
    MOVE_PRESENT,
    MOVE_DOUBLE_EDGE,
    MOVE_DIZZY_PUNCH,
    MOVE_REVERSAL,
    MOVE_SEISMIC_TOSS,
    MOVE_ENDURE,
    MOVE_PSYCH_UP,
    MOVE_CURSE,
    MOVE_HELPING_HAND,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LARVITAR
static const u16 sLarvitarEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_IRON_DEFENSE,
    MOVE_STOMP,
    MOVE_OUTRAGE,
    MOVE_FOCUS_ENERGY,
    MOVE_ANCIENT_POWER,
    MOVE_DARK_PULSE,
    MOVE_DRAGON_DANCE,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TREECKO
static const u16 sTreeckoEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_MUD_SPORT,
    MOVE_DOUBLE_KICK,
    MOVE_GRASS_WHISTLE,
    MOVE_RAZOR_WIND,
    MOVE_SYNTHESIS,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_DRAGON_BREATH,
    MOVE_SHADOW_SNEAK,
    MOVE_OUTRAGE,
    MOVE_DARK_PULSE,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TORCHIC
static const u16 sTorchicEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_AGILITY,
    MOVE_BATON_PASS,
    MOVE_CRUSH_CLAW,
    MOVE_FEATHER_DANCE,
    MOVE_REVERSAL,
    MOVE_ENDURE,
    MOVE_SWAGGER,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MUDKIP
static const u16 sMudkipEggMoveLearnset_Kismet[] = {
    MOVE_REFRESH,
    MOVE_ANCIENT_POWER,
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_DOUBLE_EDGE,
    MOVE_SLUDGE,
    MOVE_WHIRLPOOL,
    MOVE_YAWN,
    MOVE_UPROAR,
    MOVE_CURSE,
    MOVE_STOMP,
    MOVE_ICE_BALL,
    MOVE_MIRROR_COAT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_POOCHYENA
static const u16 sPoochyenaEggMoveLearnset_Kismet[] = {
    MOVE_ASTONISH,
    MOVE_PLAY_ROUGH,
    MOVE_POISON_FANG,
    MOVE_COVET,
    MOVE_LEER,
    MOVE_SHADOW_SNEAK,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ZIGZAGOON
static const u16 sZigzagoonEggMoveLearnset_Kismet[] = {
    MOVE_CHARM,
    MOVE_PURSUIT,
    MOVE_HELPING_HAND,
    MOVE_EXTREME_SPEED,
    MOVE_MUD_SLAP,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LOTAD
static const u16 sLotadEggMoveLearnset_Kismet[] = {
    MOVE_SYNTHESIS,
    MOVE_COUNTER,
    MOVE_RAZOR_LEAF,
    MOVE_SWEET_SCENT,
    MOVE_LEECH_SEED,
    MOVE_FLAIL,
    MOVE_WATER_GUN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEEDOT
static const u16 sSeedotEggMoveLearnset_Kismet[] = {
    MOVE_LEECH_SEED,
    MOVE_AMNESIA,
    MOVE_QUICK_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_TAKE_DOWN,
    MOVE_FALSE_SWIPE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RALTS
static const u16 sRaltsEggMoveLearnset_Kismet[] = {
    MOVE_DISABLE,
    MOVE_CONFUSE_RAY,
    MOVE_ENCORE,
    MOVE_HYPNOSIS,
    MOVE_PLAY_ROUGH,
    MOVE_WILL_O_WISP,
    MOVE_MEAN_LOOK,
    MOVE_MEMENTO,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SURSKIT
static const u16 sSurskitEggMoveLearnset_Kismet[] = {
    MOVE_FORESIGHT,
    MOVE_MUD_SHOT,
    MOVE_SIGNAL_BEAM,
    MOVE_PSYBEAM,
    MOVE_HYDRO_PUMP,
    MOVE_MIND_READER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHROOMISH
static const u16 sShroomishEggMoveLearnset_Kismet[] = {
    MOVE_FAKE_TEARS,
    MOVE_SWAGGER,
    MOVE_CHARM,
    MOVE_FALSE_SWIPE,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLAKOTH
static const u16 sSlakothEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_BODY_SLAM,
    MOVE_SNORE,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NINCADA
static const u16 sNincadaEggMoveLearnset_Kismet[] = {
    MOVE_ENDURE,
    MOVE_BUG_BUZZ,
    MOVE_FAINT_ATTACK,
    MOVE_MUD_SLAP,
    MOVE_GUST,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MAKUHITA
static const u16 sMakuhitaEggMoveLearnset_Kismet[] = {
    MOVE_FAINT_ATTACK,
    MOVE_DETECT,
    MOVE_FORESIGHT,
    MOVE_HELPING_HAND,
    MOVE_CROSS_CHOP,
    MOVE_REVENGE,
    MOVE_DYNAMIC_PUNCH,
    MOVE_COUNTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NOSEPASS
static const u16 sNosepassEggMoveLearnset_Kismet[] = {
    MOVE_MAGNITUDE,
    MOVE_BLOCK,
    MOVE_DOUBLE_EDGE,
    MOVE_ROLLOUT,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKITTY
static const u16 sSkittyEggMoveLearnset_Kismet[] = {
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_HYPER_VOICE,
    MOVE_UPROAR,
    MOVE_FAKE_TEARS,
    MOVE_WISH,
    MOVE_BATON_PASS,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ARON
static const u16 sAronEggMoveLearnset_Kismet[] = {
    MOVE_ENDEAVOR,
    MOVE_CURSE,
    MOVE_SCREECH,
    MOVE_BODY_SLAM,
    MOVE_STOMP,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MEDITITE
static const u16 sMedititeEggMoveLearnset_Kismet[] = {
    MOVE_FIRE_PUNCH,
    MOVE_PSYCHO_CUT,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_FORESIGHT,
    MOVE_FAKE_OUT,
    MOVE_BATON_PASS,
    MOVE_DYNAMIC_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ELECTRIKE
static const u16 sElectrikeEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_HEADBUTT,
    MOVE_UPROAR,
    MOVE_CURSE,
    MOVE_SWIFT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CARVANHA
static const u16 sCarvanhaEggMoveLearnset_Kismet[] = {
    MOVE_HYDRO_PUMP,
    MOVE_ANCIENT_POWER,
    MOVE_DOUBLE_EDGE,
    MOVE_SKULL_BASH,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WAILMER
static const u16 sWailmerEggMoveLearnset_Kismet[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_DEFENSE_CURL,
    MOVE_THRASH,
    MOVE_SWAGGER,
    MOVE_SNORE,
    MOVE_SLEEP_TALK,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NUMEL
static const u16 sNumelEggMoveLearnset_Kismet[] = {
    MOVE_HOWL,
    MOVE_ANCIENT_POWER,
    MOVE_HEAT_WAVE,
    MOVE_SPIT_UP,
    MOVE_SWALLOW,
    MOVE_STOCKPILE,
    MOVE_YAWN,
    MOVE_SCARY_FACE,
    MOVE_BODY_SLAM,
    MOVE_ROLLOUT,
    MOVE_DEFENSE_CURL,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TORKOAL
static const u16 sTorkoalEggMoveLearnset_Kismet[] = {
    MOVE_ERUPTION,
    MOVE_EARTHQUAKE,
    MOVE_SKULL_BASH,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_SLEEP_TALK,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPINDA
static const u16 sSpindaEggMoveLearnset_Kismet[] = {
    MOVE_ENCORE,
    MOVE_PSYCHO_CUT,
    MOVE_ROCK_SLIDE,
    MOVE_ASSIST,
    MOVE_DISABLE,
    MOVE_FAKE_OUT,
    MOVE_BATON_PASS,
    MOVE_WISH,
    MOVE_TRICK,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SWABLU
static const u16 sSwabluEggMoveLearnset_Kismet[] = {
    MOVE_AGILITY,
    MOVE_PLAY_ROUGH,
    MOVE_HAZE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ZANGOOSE
static const u16 sZangooseEggMoveLearnset_Kismet[] = {
    MOVE_CRUSH_CLAW,
    MOVE_COUNTER,
    MOVE_FAINT_ATTACK,
    MOVE_REVERSAL,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEVIPER
static const u16 sSeviperEggMoveLearnset_Kismet[] = {
    MOVE_CRUNCH,
    MOVE_GLARE,
    MOVE_POISON_TAIL,
    MOVE_ACID,
    MOVE_BITE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BARBOACH
static const u16 sBarboachEggMoveLearnset_Kismet[] = {
    MOVE_THRASH,
    MOVE_DRAGON_DANCE,
    MOVE_FLAIL,
    MOVE_HYDRO_PUMP,
    MOVE_EARTH_POWER,
    MOVE_TAKE_DOWN,
    MOVE_WHIRLPOOL,
    MOVE_SPARK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CORPHISH
static const u16 sCorphishEggMoveLearnset_Kismet[] = {
    MOVE_MUD_SPORT,
    MOVE_DRAGON_DANCE,
    MOVE_KNOCK_OFF,
    MOVE_METAL_CLAW,
    MOVE_ENDEAVOR,
    MOVE_CROSS_POISON,
    MOVE_REVENGE,
    MOVE_BODY_SLAM,
    MOVE_ANCIENT_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LILEEP
static const u16 sLileepEggMoveLearnset_Kismet[] = {
    MOVE_BARRIER,
    MOVE_CURSE,
    MOVE_TICKLE,
    MOVE_RECOVER,
    MOVE_MIRROR_COAT,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ANORITH
static const u16 sAnorithEggMoveLearnset_Kismet[] = {
    MOVE_RAPID_SPIN,
    MOVE_CURSE,
    MOVE_SAND_ATTACK,
    MOVE_SCREECH,
    MOVE_KNOCK_OFF,
    MOVE_SWORDS_DANCE,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FEEBAS
static const u16 sFeebasEggMoveLearnset_Kismet[] = {
    MOVE_MIRROR_COAT,
    MOVE_DRAGON_PULSE,
    MOVE_HAZE,
    MOVE_MIST,
    MOVE_TICKLE,
    MOVE_DRAGON_BREATH,
    MOVE_MUD_SPORT,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CASTFORM
static const u16 sCastformNormalEggMoveLearnset_Kismet[] = {
    MOVE_FUTURE_SIGHT,
    MOVE_AMNESIA,
    MOVE_DISABLE,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHUPPET
static const u16 sShuppetEggMoveLearnset_Kismet[] = {
    MOVE_DISABLE,
    MOVE_CONFUSE_RAY,
    MOVE_PURSUIT,
    MOVE_DESTINY_BOND,
    MOVE_FORESIGHT,
    MOVE_ASTONISH,
    MOVE_REVENGE,
    MOVE_EXTRASENSORY,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DUSKULL
static const u16 sDuskullEggMoveLearnset_Kismet[] = {
    MOVE_IMPRISON,
    MOVE_DARK_PULSE,
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_ASTONISH,
    MOVE_GRUDGE,
    MOVE_MEMENTO,
    MOVE_FAINT_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TROPIUS
static const u16 sTropiusEggMoveLearnset_Kismet[] = {
    MOVE_HEADBUTT,
    MOVE_SLAM,
    MOVE_CURSE,
    MOVE_DRAGON_DANCE,
    MOVE_LEAF_BLADE,
    MOVE_SYNTHESIS,
    MOVE_RAZOR_WIND,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHIMECHO
static const u16 sChimechoEggMoveLearnset_Kismet[] = {
    MOVE_DISABLE,
    MOVE_CURSE,
    MOVE_HYPNOSIS,
    MOVE_BOOMBURST,
    MOVE_FUTURE_SIGHT,
    MOVE_RECOVER,
    MOVE_WISH,
    MOVE_DREAM_EATER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ABSOL
static const u16 sAbsolEggMoveLearnset_Kismet[] = {
    MOVE_BATON_PASS,
    MOVE_FALSE_SWIPE,
    MOVE_MEAN_LOOK,
    MOVE_MEGAHORN,
    MOVE_FAINT_ATTACK,
    MOVE_PLAY_ROUGH,
    MOVE_DOUBLE_EDGE,
    MOVE_SHADOW_SNEAK,
    MOVE_MAGIC_COAT,
    MOVE_CURSE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNORUNT
static const u16 sSnoruntEggMoveLearnset_Kismet[] = {
    MOVE_BLOCK,
    MOVE_BIDE,
    MOVE_DISABLE,
    MOVE_ROLLOUT,
    MOVE_WEATHER_BALL,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CLAMPERL
static const u16 sClamperlEggMoveLearnset_Kismet[] = {
    MOVE_REFRESH,
    MOVE_MUDDY_WATER,
    MOVE_MUD_SPORT,
    MOVE_BODY_SLAM,
    MOVE_SUPERSONIC,
    MOVE_BARRIER,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RELICANTH
static const u16 sRelicanthEggMoveLearnset_Kismet[] = {
    MOVE_MAGNITUDE,
    MOVE_SKULL_BASH,
    MOVE_WATER_SPORT,
    MOVE_AMNESIA,
    MOVE_MUDDY_WATER,
    MOVE_MUD_SLAP,
    MOVE_SNORE,
    MOVE_SLEEP_TALK,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LUVDISC
static const u16 sLuvdiscEggMoveLearnset_Kismet[] = {
    MOVE_SPLASH,
    MOVE_SUPERSONIC,
    MOVE_WATER_SPORT,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BRONZOR
static const u16 sBronzorEggMoveLearnset_Kismet[] = {
    MOVE_GRASS_WHISTLE,
    MOVE_ACID,
    MOVE_LOW_KICK,
    MOVE_SMELLING_SALTS,
    MOVE_TEETER_DANCE,
    MOVE_DYNAMIC_PUNCH,
    MOVE_COUNTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPIRITOMB
static const u16 sSpiritombEggMoveLearnset_Kismet[] = {
    MOVE_CURSE,
    MOVE_PURSUIT,
    MOVE_PAIN_SPLIT,
    MOVE_NIGHT_SHADE,
    MOVE_DISABLE,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GIBLE
static const u16 sGibleEggMoveLearnset_Kismet[] = {
    MOVE_HYDRO_PUMP,
    MOVE_DRAGON_PULSE,
    MOVE_THRASH,
    MOVE_DRAGON_RAGE,
    MOVE_TWISTER,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RIOLU
static const u16 sRioluEggMoveLearnset_Kismet[] = {
    MOVE_BLAZE_KICK,
    MOVE_CRUNCH,
    MOVE_CROSS_CHOP,
    MOVE_MUD_SLAP,
    MOVE_AGILITY,
    MOVE_MIND_READER,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKORUPI
static const u16 sSkorupiEggMoveLearnset_Kismet[] = {
    MOVE_STOCKPILE,
    MOVE_SCARY_FACE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_BODY_SLAM,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VANILLITE
static const u16 sVanilliteEggMoveLearnset_Kismet[] = {
    MOVE_ENCORE,
    MOVE_BODY_SLAM,
    MOVE_FUTURE_SIGHT,
    MOVE_AMNESIA,
    MOVE_MIRROR_COAT,
    MOVE_EXTRASENSORY,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TYNAMO
static const u16 sTynamoEggMoveLearnset_Kismet[] = {
    MOVE_WATER_SPORT,
    MOVE_SIGNAL_BEAM,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_YAWN,
    MOVE_ROCK_SLIDE,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AXEW
static const u16 sAxewEggMoveLearnset_Kismet[] = {
    MOVE_TAKE_DOWN,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_LUNGE,
    MOVE_MUD_SHOT,
    MOVE_DIG,
    MOVE_PLAY_ROUGH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MIENFOO
static const u16 sMienfooEggMoveLearnset_Kismet[] = {
    MOVE_COUNTER,
    MOVE_FOCUS_PUNCH,
    MOVE_MEDITATE,
    MOVE_BLAZE_KICK,
    MOVE_REVENGE,
    MOVE_MIND_READER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RUFFLET
static const u16 sRuffletEggMoveLearnset_Kismet[] = {
    MOVE_MIST,
    MOVE_TWISTER,
    MOVE_AGILITY,
    MOVE_GUST,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VULLABY
static const u16 sVullabyEggMoveLearnset_Kismet[] = {
    MOVE_FEATHER_DANCE,
    MOVE_PURSUIT,
    MOVE_SKY_ATTACK,
    MOVE_COUNTER,
    MOVE_REVENGE,
    MOVE_CURSE,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LARVESTA
static const u16 sLarvestaEggMoveLearnset_Kismet[] = {
    MOVE_FLAMETHROWER,
    MOVE_MIRROR_COAT,
    MOVE_SPLASH,
    MOVE_ANCIENT_POWER,
    MOVE_MAGIC_COAT,
    MOVE_SCORCHING_SANDS,
    MOVE_GIGA_DRAIN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FLETCHLING
static const u16 sFletchlingEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_UPROAR,
    MOVE_FLAMETHROWER,
    MOVE_FORESIGHT,
    MOVE_RAZOR_WIND,
    MOVE_STEEL_WING,
    MOVE_AIR_SLASH,
    MOVE_AIR_CUTTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FOMANTIS
static const u16 sFomantisEggMoveLearnset_Kismet[] = {
    MOVE_SOLAR_BEAM,
    MOVE_LEAF_BLADE,
    MOVE_SWEET_SCENT,
    MOVE_GRASS_WHISTLE,
    MOVE_SYNTHESIS,
    MOVE_AROMATHERAPY,
    MOVE_ENERGY_BALL,
    MOVE_MAGICAL_LEAF,
    MOVE_DOUBLE_EDGE,
    MOVE_NATURE_POWER,
    MOVE_GRASS_KNOT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MIMIKYU
static const u16 sMimikyuDisguisedEggMoveLearnset_Kismet[] = {
    MOVE_CHARM,
    MOVE_CONFUSE_RAY,
    MOVE_MIMIC,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_IMPIDIMP
static const u16 sImpidimpEggMoveLearnset_Kismet[] = {
    MOVE_TORMENT,
    MOVE_PURSUIT,
    MOVE_SHADOW_SNEAK,
    MOVE_MUD_SLAP,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WATTREL
static const u16 sWattrelEggMoveLearnset_Kismet[] = {
    MOVE_PURSUIT,
    MOVE_SUPERSONIC,
    MOVE_WHIRLWIND,
    MOVE_REFRESH,
    MOVE_MIRROR_MOVE,
    MOVE_RAGE,
    MOVE_SKY_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TINKATINK
static const u16 sTinkatinkEggMoveLearnset_Kismet[] = {
    MOVE_DEFENSE_CURL,
    MOVE_IRON_DEFENSE,
    MOVE_TAUNT,
    MOVE_HEADBUTT,
    MOVE_ROLLOUT,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BOMBIRDIER
static const u16 sBombirdierEggMoveLearnset_Kismet[] = {
    MOVE_PRESENT,
    MOVE_WHIRLWIND,
    MOVE_DRILL_PECK,
    MOVE_MIRROR_MOVE,
    MOVE_PAY_DAY,
    MOVE_HAZE,
    MOVE_STONE_EDGE,
    MOVE_SKY_ATTACK,
    MOVE_SCARY_FACE,
    MOVE_NIGHT_SLASH,
    MOVE_PERISH_SONG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GREAVARD
static const u16 sGreavardEggMoveLearnset_Kismet[] = {
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_SAFEGUARD,
    MOVE_DOUBLE_EDGE,
    MOVE_THRASH,
    MOVE_NIGHT_SHADE,
    MOVE_HOWL,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_KISMET_FAKEMON
static const u16 sKrolucadaEggMoveLearnset_Kismet[] = {
    MOVE_BATON_PASS,
    MOVE_BUG_BUZZ,
    MOVE_ENCORE,
    MOVE_SILVER_WIND,
    MOVE_SHADOW_SNEAK,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sLarvicidEggMoveLearnset_Kismet[] = {
    MOVE_POUNCE,
    MOVE_ACID_ARMOR,
    MOVE_SMOG,
    MOVE_HEAVY_SLAM,
    MOVE_MIRROR_SHOT,
    MOVE_LUNGE,
    MOVE_UNAVAILABLE,
};

static const u16 sPurgislugEggMoveLearnset_Kismet[] = {
    MOVE_PAIN_SPLIT,
    MOVE_EXTRASENSORY,
    MOVE_MIND_READER,
    MOVE_MAGICAL_LEAF,
    MOVE_GRUDGE,
    MOVE_MEMENTO,
    MOVE_UNAVAILABLE,
};

static const u16 sRaelicEggMoveLearnset_Kismet[] = {
    MOVE_MIND_READER,
    MOVE_MUD_SHOT,
    MOVE_FLAIL,
    MOVE_MAGIC_COAT,
    MOVE_EARTH_POWER,
    MOVE_GIGA_DRAIN,
    MOVE_REST,
    MOVE_UNAVAILABLE,
};

#endif
