// Kismet: original egg moves ported from pokemonHnS.
//
// Generated by .claude/eggmove_emit.py - do not hand-edit; re-run
// the script. Sparse: only species the fork retunes appear here,
// everything else falls through to gEggMoves_Gen3[].
//
// Six fork lists are deliberately absent - see the script's
// docstring. Four are copy-paste leftovers from species swaps;
// Drapion's and Gallade's could never fire, as nothing hatches
// as either.

#include "constants/moves.h"

#if P_FAMILY_BULBASAUR
static const u16 sBulbasaurEggMoveLearnset_KismetGen3[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_SKULL_BASH,
    MOVE_SAFEGUARD,
    MOVE_CHARM,
    MOVE_PETAL_DANCE,
    MOVE_MAGICAL_LEAF,
    MOVE_GRASS_WHISTLE,
    MOVE_FALSE_SWIPE,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHARMANDER
static const u16 sCharmanderEggMoveLearnset_KismetGen3[] = {
    MOVE_BELLY_DRUM,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_BITE,
    MOVE_OUTRAGE,
    MOVE_BEAT_UP,
    MOVE_SWORDS_DANCE,
    MOVE_FALSE_SWIPE,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SQUIRTLE
static const u16 sSquirtleEggMoveLearnset_KismetGen3[] = {
    MOVE_MIRROR_COAT,
    MOVE_HAZE,
    MOVE_MIST,
    MOVE_FORESIGHT,
    MOVE_FLAIL,
    MOVE_REFRESH,
    MOVE_MUD_SPORT,
    MOVE_FALSE_SWIPE,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PIDGEY
static const u16 sPidgeyEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_STEEL_WING,
    MOVE_AIR_CUTTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RATTATA
static const u16 sRattataEggMoveLearnset_KismetGen3[] = {
    MOVE_SCREECH,
    MOVE_FLAME_WHEEL,
    MOVE_FURY_SWIPES,
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_REVERSAL,
    MOVE_UPROAR,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPEAROW
static const u16 sSpearowEggMoveLearnset_KismetGen3[] = {
    MOVE_FAINT_ATTACK,
    MOVE_FALSE_SWIPE,
    MOVE_SCARY_FACE,
    MOVE_QUICK_ATTACK,
    MOVE_TRI_ATTACK,
    MOVE_ASTONISH,
    MOVE_SKY_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EKANS
static const u16 sEkansEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_SLAM,
    MOVE_SPITE,
    MOVE_BEAT_UP,
    MOVE_POISON_FANG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PIKACHU
#if P_GEN_2_CROSS_EVOS
static const u16 sPichuEggMoveLearnset_KismetGen3[] = {
    MOVE_REVERSAL,
    MOVE_BIDE,
    MOVE_PRESENT,
    MOVE_ENCORE,
    MOVE_DOUBLE_SLAP,
    MOVE_WISH,
    MOVE_CHARGE,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_SANDSHREW
static const u16 sSandshrewEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_FALSE_SWIPE,
    MOVE_SAFEGUARD,
    MOVE_COUNTER,
    MOVE_NEEDLE_ARM,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_METAL_CLAW,
    MOVE_SWORDS_DANCE,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NIDORAN
static const u16 sNidoranFEggMoveLearnset_KismetGen3[] = {
    MOVE_SUPERSONIC,
    MOVE_DISABLE,
    MOVE_TAKE_DOWN,
    MOVE_FOCUS_ENERGY,
    MOVE_CHARM,
    MOVE_COUNTER,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

static const u16 sNidoranMEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CLEFAIRY
#if P_GEN_2_CROSS_EVOS
static const u16 sCleffaEggMoveLearnset_KismetGen3[] = {
    MOVE_PRESENT,
    MOVE_METRONOME,
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_SPLASH,
    MOVE_MIMIC,
    MOVE_WISH,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_VULPIX
static const u16 sVulpixEggMoveLearnset_KismetGen3[] = {
    MOVE_FAINT_ATTACK,
    MOVE_HYPNOSIS,
    MOVE_FLAIL,
    MOVE_SPITE,
    MOVE_DISABLE,
    MOVE_HOWL,
    MOVE_PSYCH_UP,
    MOVE_LICK,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_JIGGLYPUFF
#if P_GEN_2_CROSS_EVOS
static const u16 sIgglybuffEggMoveLearnset_KismetGen3[] = {
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_FAINT_ATTACK,
    MOVE_WISH,
    MOVE_FAKE_TEARS,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_ZUBAT
static const u16 sZubatEggMoveLearnset_KismetGen3[] = {
    MOVE_QUICK_ATTACK,
    MOVE_PURSUIT,
    MOVE_FAINT_ATTACK,
    MOVE_SHADOW_SNEAK,
    MOVE_GUST,
    MOVE_CRUNCH,
    MOVE_WHIRLWIND,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ODDISH
static const u16 sOddishEggMoveLearnset_KismetGen3[] = {
    MOVE_SWORDS_DANCE,
    MOVE_RAZOR_LEAF,
    MOVE_FLAIL,
    MOVE_SYNTHESIS,
    MOVE_CHARM,
    MOVE_INGRAIN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PARAS
static const u16 sParasEggMoveLearnset_KismetGen3[] = {
    MOVE_FALSE_SWIPE,
    MOVE_SCREECH,
    MOVE_COUNTER,
    MOVE_PSYBEAM,
    MOVE_LEECH_SEED,
    MOVE_FLAIL,
    MOVE_SWEET_SCENT,
    MOVE_LIGHT_SCREEN,
    MOVE_PURSUIT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VENONAT
static const u16 sVenonatEggMoveLearnset_KismetGen3[] = {
    MOVE_BATON_PASS,
    MOVE_SCREECH,
    MOVE_GIGA_DRAIN,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DIGLETT
static const u16 sDiglettEggMoveLearnset_KismetGen3[] = {
    MOVE_FAINT_ATTACK,
    MOVE_SCREECH,
    MOVE_ANCIENT_POWER,
    MOVE_PURSUIT,
    MOVE_BEAT_UP,
    MOVE_UPROAR,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MEOWTH
static const u16 sMeowthEggMoveLearnset_KismetGen3[] = {
    MOVE_SPITE,
    MOVE_CHARM,
    MOVE_HYPNOSIS,
    MOVE_FALSE_SWIPE,
    MOVE_SHADOW_SNEAK,
    MOVE_AMNESIA,
    MOVE_PSYCH_UP,
    MOVE_ASSIST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PSYDUCK
static const u16 sPsyduckEggMoveLearnset_KismetGen3[] = {
    MOVE_HYPNOSIS,
    MOVE_PSYBEAM,
    MOVE_FORESIGHT,
    MOVE_LIGHT_SCREEN,
    MOVE_FUTURE_SIGHT,
    MOVE_PSYCHIC,
    MOVE_CROSS_CHOP,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MANKEY
static const u16 sMankeyEggMoveLearnset_KismetGen3[] = {
    MOVE_ROCK_SLIDE,
    MOVE_FORESIGHT,
    MOVE_MEDITATE,
    MOVE_COUNTER,
    MOVE_REVERSAL,
    MOVE_BEAT_UP,
    MOVE_REVENGE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GROWLITHE
static const u16 sGrowlitheEggMoveLearnset_KismetGen3[] = {
    MOVE_BODY_SLAM,
    MOVE_SAFEGUARD,
    MOVE_DRAGON_PULSE,
    MOVE_CRUNCH,
    MOVE_THRASH,
    MOVE_FIRE_SPIN,
    MOVE_HOWL,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_POLIWAG
static const u16 sPoliwagEggMoveLearnset_KismetGen3[] = {
    MOVE_MIST,
    MOVE_SPLASH,
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_MIND_READER,
    MOVE_WATER_SPORT,
    MOVE_ICE_BALL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ABRA
static const u16 sAbraEggMoveLearnset_KismetGen3[] = {
    MOVE_ENCORE,
    MOVE_BARRIER,
    MOVE_TRI_ATTACK,
    MOVE_KNOCK_OFF,
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MACHOP
static const u16 sMachopEggMoveLearnset_KismetGen3[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_MEDITATE,
    MOVE_ROLLING_KICK,
    MOVE_ENCORE,
    MOVE_SMELLING_SALTS,
    MOVE_COUNTER,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BELLSPROUT
static const u16 sBellsproutEggMoveLearnset_KismetGen3[] = {
    MOVE_SWORDS_DANCE,
    MOVE_ENCORE,
    MOVE_REFLECT,
    MOVE_SYNTHESIS,
    MOVE_LEECH_LIFE,
    MOVE_INGRAIN,
    MOVE_MAGICAL_LEAF,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TENTACOOL
static const u16 sTentacoolEggMoveLearnset_KismetGen3[] = {
    MOVE_AURORA_BEAM,
    MOVE_MIRROR_COAT,
    MOVE_RAPID_SPIN,
    MOVE_HAZE,
    MOVE_SAFEGUARD,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GEODUDE
static const u16 sGeodudeEggMoveLearnset_KismetGen3[] = {
    MOVE_MEGA_PUNCH,
    MOVE_ROCK_SLIDE,
    MOVE_BLOCK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PONYTA
static const u16 sPonytaEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAME_WHEEL,
    MOVE_SCORCHING_SANDS,
    MOVE_THRASH,
    MOVE_DOUBLE_KICK,
    MOVE_HYPNOSIS,
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLOWPOKE
static const u16 sSlowpokeEggMoveLearnset_KismetGen3[] = {
    MOVE_SAFEGUARD,
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_STOMP,
    MOVE_MUD_SPORT,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FARFETCHD
static const u16 sFarfetchdEggMoveLearnset_KismetGen3[] = {
    MOVE_STEEL_WING,
    MOVE_FORESIGHT,
    MOVE_MIRROR_MOVE,
    MOVE_GUST,
    MOVE_QUICK_ATTACK,
    MOVE_FLAIL,
    MOVE_FEATHER_DANCE,
    MOVE_FALSE_SWIPE,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DODUO
static const u16 sDoduoEggMoveLearnset_KismetGen3[] = {
    MOVE_QUICK_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_HAZE,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEEL
static const u16 sSeelEggMoveLearnset_KismetGen3[] = {
    MOVE_LICK,
    MOVE_PERISH_SONG,
    MOVE_DISABLE,
    MOVE_HORN_DRILL,
    MOVE_SLAM,
    MOVE_SAFEGUARD,
    MOVE_ENCORE,
    MOVE_FAKE_OUT,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GRIMER
static const u16 sGrimerEggMoveLearnset_KismetGen3[] = {
    MOVE_HAZE,
    MOVE_MEAN_LOOK,
    MOVE_SHADOW_SNEAK,
    MOVE_LICK,
    MOVE_IMPRISON,
    MOVE_CURSE,
    MOVE_SHADOW_PUNCH,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHELLDER
static const u16 sShellderEggMoveLearnset_KismetGen3[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_TAKE_DOWN,
    MOVE_BARRIER,
    MOVE_RAPID_SPIN,
    MOVE_SCREECH,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GASTLY
static const u16 sGastlyEggMoveLearnset_KismetGen3[] = {
    MOVE_PSYWAVE,
    MOVE_PERISH_SONG,
    MOVE_HAZE,
    MOVE_ASTONISH,
    MOVE_WILL_O_WISP,
    MOVE_SHADOW_SNEAK,
    MOVE_GRUDGE,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ONIX
static const u16 sOnixEggMoveLearnset_KismetGen3[] = {
    MOVE_ROCK_SLIDE,
    MOVE_FLAIL,
    MOVE_EXPLOSION,
    MOVE_BLOCK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DROWZEE
static const u16 sDrowzeeEggMoveLearnset_KismetGen3[] = {
    MOVE_BARRIER,
    MOVE_ASSIST,
    MOVE_ROLE_PLAY,
    MOVE_SHADOW_SNEAK,
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KRABBY
static const u16 sKrabbyEggMoveLearnset_KismetGen3[] = {
    MOVE_DIG,
    MOVE_HAZE,
    MOVE_AMNESIA,
    MOVE_FLAIL,
    MOVE_SLAM,
    MOVE_KNOCK_OFF,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EXEGGCUTE
static const u16 sExeggcuteEggMoveLearnset_KismetGen3[] = {
    MOVE_SYNTHESIS,
    MOVE_MOONLIGHT,
    MOVE_REFLECT,
    MOVE_ANCIENT_POWER,
    MOVE_PSYCH_UP,
    MOVE_INGRAIN,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CUBONE
static const u16 sCuboneEggMoveLearnset_KismetGen3[] = {
    MOVE_ROCK_SLIDE,
    MOVE_ANCIENT_POWER,
    MOVE_BELLY_DRUM,
    MOVE_SCREECH,
    MOVE_SKULL_BASH,
    MOVE_PERISH_SONG,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HITMONS
#if P_GEN_2_CROSS_EVOS
static const u16 sTyrogueEggMoveLearnset_KismetGen3[] = {
    MOVE_RAPID_SPIN,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_LICKITUNG
static const u16 sLickitungEggMoveLearnset_KismetGen3[] = {
    MOVE_BELLY_DRUM,
    MOVE_MAGNITUDE,
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_SMELLING_SALTS,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KOFFING
static const u16 sKoffingEggMoveLearnset_KismetGen3[] = {
    MOVE_SCREECH,
    MOVE_PSYWAVE,
    MOVE_PSYBEAM,
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RHYHORN
static const u16 sRhyhornEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_MAGNITUDE,
    MOVE_SWORDS_DANCE,
    MOVE_CURSE,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHANSEY
static const u16 sChanseyEggMoveLearnset_KismetGen3[] = {
    MOVE_PRESENT,
    MOVE_METRONOME,
    MOVE_HEAL_BELL,
    MOVE_AROMATHERAPY,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TANGELA
static const u16 sTangelaEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_CONFUSION,
    MOVE_MEGA_DRAIN,
    MOVE_REFLECT,
    MOVE_AMNESIA,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KANGASKHAN
static const u16 sKangaskhanEggMoveLearnset_KismetGen3[] = {
    MOVE_STOMP,
    MOVE_FORESIGHT,
    MOVE_FOCUS_ENERGY,
    MOVE_SAFEGUARD,
    MOVE_DISABLE,
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HORSEA
static const u16 sHorseaEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_AURORA_BEAM,
    MOVE_OCTAZOOKA,
    MOVE_DISABLE,
    MOVE_SPLASH,
    MOVE_DRAGON_RAGE,
    MOVE_DRAGON_BREATH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GOLDEEN
static const u16 sGoldeenEggMoveLearnset_KismetGen3[] = {
    MOVE_PSYBEAM,
    MOVE_HAZE,
    MOVE_HYDRO_PUMP,
    MOVE_SLEEP_TALK,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MR_MIME
static const u16 sMrMimeEggMoveLearnset_KismetGen3[] = {
    MOVE_FUTURE_SIGHT,
    MOVE_HYPNOSIS,
    MOVE_MIMIC,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SCYTHER
static const u16 sScytherEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_SAFEGUARD,
    MOVE_BATON_PASS,
    MOVE_RAZOR_WIND,
    MOVE_REVERSAL,
    MOVE_LIGHT_SCREEN,
    MOVE_ENDURE,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_JYNX
#if P_GEN_2_CROSS_EVOS
static const u16 sSmoochumEggMoveLearnset_KismetGen3[] = {
    MOVE_MEDITATE,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_BODY_SLAM,
    MOVE_WISH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_ELECTABUZZ
#if P_GEN_2_CROSS_EVOS
static const u16 sElekidEggMoveLearnset_KismetGen3[] = {
    MOVE_KARATE_CHOP,
    MOVE_BARRIER,
    MOVE_ROLLING_KICK,
    MOVE_MEDITATE,
    MOVE_CROSS_CHOP,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_MAGMAR
#if P_GEN_2_CROSS_EVOS
static const u16 sMagbyEggMoveLearnset_KismetGen3[] = {
    MOVE_KARATE_CHOP,
    MOVE_MEGA_PUNCH,
    MOVE_BARRIER,
    MOVE_SCREECH,
    MOVE_CROSS_CHOP,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

#endif
#endif
#if P_FAMILY_PINSIR
static const u16 sPinsirEggMoveLearnset_KismetGen3[] = {
    MOVE_FURY_ATTACK,
    MOVE_FLAIL,
    MOVE_BIND,
    MOVE_FALSE_SWIPE,
    MOVE_FAINT_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LAPRAS
static const u16 sLaprasEggMoveLearnset_KismetGen3[] = {
    MOVE_FORESIGHT,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_REFRESH,
    MOVE_DRAGON_DANCE,
    MOVE_CURSE,
    MOVE_SLEEP_TALK,
    MOVE_HORN_DRILL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_EEVEE
static const u16 sEeveeEggMoveLearnset_KismetGen3[] = {
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_ENDURE,
    MOVE_CURSE,
    MOVE_TICKLE,
    MOVE_FALSE_SWIPE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_OMANYTE
static const u16 sOmanyteEggMoveLearnset_KismetGen3[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_AURORA_BEAM,
    MOVE_SLAM,
    MOVE_SUPERSONIC,
    MOVE_HAZE,
    MOVE_ROCK_SLIDE,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_KABUTO
static const u16 sKabutoEggMoveLearnset_KismetGen3[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_AURORA_BEAM,
    MOVE_RAPID_SPIN,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_KNOCK_OFF,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AERODACTYL
static const u16 sAerodactylEggMoveLearnset_KismetGen3[] = {
    MOVE_WHIRLWIND,
    MOVE_PURSUIT,
    MOVE_FORESIGHT,
    MOVE_STEEL_WING,
    MOVE_DRAGON_BREATH,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNORLAX
static const u16 sSnorlaxEggMoveLearnset_KismetGen3[] = {
    MOVE_LICK,
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DRATINI
static const u16 sDratiniEggMoveLearnset_KismetGen3[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_MIST,
    MOVE_HAZE,
    MOVE_SUPERSONIC,
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHIKORITA
static const u16 sChikoritaEggMoveLearnset_KismetGen3[] = {
    MOVE_VINE_WHIP,
    MOVE_LEECH_SEED,
    MOVE_COUNTER,
    MOVE_ANCIENT_POWER,
    MOVE_SAFEGUARD,
    MOVE_FLAIL,
    MOVE_NATURE_POWER,
    MOVE_INGRAIN,
    MOVE_GRASS_WHISTLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CYNDAQUIL
static const u16 sCyndaquilEggMoveLearnset_KismetGen3[] = {
    MOVE_FURY_SWIPES,
    MOVE_QUICK_ATTACK,
    MOVE_REVERSAL,
    MOVE_THRASH,
    MOVE_FORESIGHT,
    MOVE_COVET,
    MOVE_HOWL,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TOTODILE
static const u16 sTotodileEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_THRASH,
    MOVE_HYDRO_PUMP,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_MUD_SPORT,
    MOVE_WATER_SPORT,
    MOVE_DRAGON_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SENTRET
static const u16 sSentretEggMoveLearnset_KismetGen3[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_FOCUS_ENERGY,
    MOVE_REVERSAL,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_ASSIST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOOTHOOT
static const u16 sHoothootEggMoveLearnset_KismetGen3[] = {
    MOVE_MIRROR_MOVE,
    MOVE_SUPERSONIC,
    MOVE_FAINT_ATTACK,
    MOVE_NIGHT_SHADE,
    MOVE_WING_ATTACK,
    MOVE_BIDE,
    MOVE_OMINOUS_WIND,
    MOVE_SHADOW_SNEAK,
    MOVE_WHIRLWIND,
    MOVE_SKY_ATTACK,
    MOVE_FEATHER_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LEDYBA
static const u16 sLedybaEggMoveLearnset_KismetGen3[] = {
    MOVE_PSYBEAM,
    MOVE_BIDE,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPINARAK
static const u16 sSpinarakEggMoveLearnset_KismetGen3[] = {
    MOVE_PSYBEAM,
    MOVE_DISABLE,
    MOVE_SONIC_BOOM,
    MOVE_BATON_PASS,
    MOVE_PURSUIT,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHINCHOU
static const u16 sChinchouEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_SCREECH,
    MOVE_AMNESIA,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TOGEPI
static const u16 sTogepiEggMoveLearnset_KismetGen3[] = {
    MOVE_PRESENT,
    MOVE_MIRROR_MOVE,
    MOVE_PECK,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_SUBSTITUTE,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NATU
static const u16 sNatuEggMoveLearnset_KismetGen3[] = {
    MOVE_HAZE,
    MOVE_DRILL_PECK,
    MOVE_QUICK_ATTACK,
    MOVE_FAINT_ATTACK,
    MOVE_STEEL_WING,
    MOVE_PSYCH_UP,
    MOVE_FEATHER_DANCE,
    MOVE_SHADOW_SNEAK,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MAREEP
static const u16 sMareepEggMoveLearnset_KismetGen3[] = {
    MOVE_TAKE_DOWN,
    MOVE_BODY_SLAM,
    MOVE_SAFEGUARD,
    MOVE_SCREECH,
    MOVE_REFLECT,
    MOVE_ODOR_SLEUTH,
    MOVE_CHARGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MARILL
static const u16 sMarillEggMoveLearnset_KismetGen3[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_PRESENT,
    MOVE_AMNESIA,
    MOVE_FUTURE_SIGHT,
    MOVE_BELLY_DRUM,
    MOVE_PERISH_SONG,
    MOVE_SUPERSONIC,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SUDOWOODO
static const u16 sSudowoodoEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_SELF_DESTRUCT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOPPIP
static const u16 sHoppipEggMoveLearnset_KismetGen3[] = {
    MOVE_CONFUSION,
    MOVE_ENCORE,
    MOVE_DOUBLE_EDGE,
    MOVE_REFLECT,
    MOVE_AMNESIA,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AIPOM
static const u16 sAipomEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_SCREECH,
    MOVE_PURSUIT,
    MOVE_AGILITY,
    MOVE_SPITE,
    MOVE_SLAM,
    MOVE_SHADOW_SNEAK,
    MOVE_DOUBLE_SLAP,
    MOVE_BEAT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SUNKERN
static const u16 sSunkernEggMoveLearnset_KismetGen3[] = {
    MOVE_GRASS_WHISTLE,
    MOVE_ENCORE,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_CURSE,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_YANMA
static const u16 sYanmaEggMoveLearnset_KismetGen3[] = {
    MOVE_WHIRLWIND,
    MOVE_REVERSAL,
    MOVE_LEECH_LIFE,
    MOVE_SIGNAL_BEAM,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WOOPER
static const u16 sWooperEggMoveLearnset_KismetGen3[] = {
    MOVE_BODY_SLAM,
    MOVE_ANCIENT_POWER,
    MOVE_SAFEGUARD,
    MOVE_CURSE,
    MOVE_MUD_SPORT,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MURKROW
static const u16 sMurkrowEggMoveLearnset_KismetGen3[] = {
    MOVE_WHIRLWIND,
    MOVE_DRILL_PECK,
    MOVE_MIRROR_MOVE,
    MOVE_WING_ATTACK,
    MOVE_PAY_DAY,
    MOVE_SKY_ATTACK,
    MOVE_HEAT_WAVE,
    MOVE_CONFUSE_RAY,
    MOVE_FEATHER_DANCE,
    MOVE_SHADOW_SNEAK,
    MOVE_PERISH_SONG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MISDREAVUS
static const u16 sMisdreavusEggMoveLearnset_KismetGen3[] = {
    MOVE_SCREECH,
    MOVE_DESTINY_BOND,
    MOVE_SHADOW_SNEAK,
    MOVE_PSYCH_UP,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GIRAFARIG
static const u16 sGirafarigEggMoveLearnset_KismetGen3[] = {
    MOVE_TAKE_DOWN,
    MOVE_AMNESIA,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_BEAT_UP,
    MOVE_PSYCH_UP,
    MOVE_WISH,
    MOVE_MAGIC_COAT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PINECO
static const u16 sPinecoEggMoveLearnset_KismetGen3[] = {
    MOVE_REFLECT,
    MOVE_PIN_MISSILE,
    MOVE_FLAIL,
    MOVE_SWIFT,
    MOVE_COUNTER,
    MOVE_SAND_TOMB,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DUNSPARCE
static const u16 sDunsparceEggMoveLearnset_KismetGen3[] = {
    MOVE_BIDE,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_BITE,
    MOVE_HEADBUTT,
    MOVE_ASTONISH,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GLIGAR
static const u16 sGligarEggMoveLearnset_KismetGen3[] = {
    MOVE_METAL_CLAW,
    MOVE_WING_ATTACK,
    MOVE_FALSE_SWIPE,
    MOVE_RAZOR_WIND,
    MOVE_COUNTER,
    MOVE_SAND_TOMB,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNUBBULL
static const u16 sSnubbullEggMoveLearnset_KismetGen3[] = {
    MOVE_METRONOME,
    MOVE_FAINT_ATTACK,
    MOVE_REFLECT,
    MOVE_PRESENT,
    MOVE_CRUNCH,
    MOVE_HEAL_BELL,
    MOVE_SNORE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_QWILFISH
static const u16 sQwilfishEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_BUBBLE_BEAM,
    MOVE_SUPERSONIC,
    MOVE_ASTONISH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHUCKLE
static const u16 sShuckleEggMoveLearnset_KismetGen3[] = {
    MOVE_SWEET_SCENT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HERACROSS
static const u16 sHeracrossEggMoveLearnset_KismetGen3[] = {
    MOVE_HARDEN,
    MOVE_BIDE,
    MOVE_FLAIL,
    MOVE_FALSE_SWIPE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNEASEL
static const u16 sSneaselEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_SPITE,
    MOVE_FORESIGHT,
    MOVE_REFLECT,
    MOVE_BITE,
    MOVE_LOW_KICK,
    MOVE_CRUSH_CLAW,
    MOVE_SHADOW_SNEAK,
    MOVE_FAKE_OUT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TEDDIURSA
static const u16 sTeddiursaEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_TAKE_DOWN,
    MOVE_SEISMIC_TOSS,
    MOVE_COUNTER,
    MOVE_METAL_CLAW,
    MOVE_FAKE_TEARS,
    MOVE_YAWN,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLUGMA
static const u16 sSlugmaEggMoveLearnset_KismetGen3[] = {
    MOVE_ACID_ARMOR,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SWINUB
static const u16 sSwinubEggMoveLearnset_KismetGen3[] = {
    MOVE_TAKE_DOWN,
    MOVE_BITE,
    MOVE_BODY_SLAM,
    MOVE_ROCK_SLIDE,
    MOVE_ANCIENT_POWER,
    MOVE_MUD_SHOT,
    MOVE_ICICLE_SPEAR,
    MOVE_DOUBLE_EDGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CORSOLA
static const u16 sCorsolaEggMoveLearnset_KismetGen3[] = {
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_MIST,
    MOVE_AMNESIA,
    MOVE_BARRIER,
    MOVE_INGRAIN,
    MOVE_CONFUSE_RAY,
    MOVE_ICICLE_SPEAR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_REMORAID
static const u16 sRemoraidEggMoveLearnset_KismetGen3[] = {
    MOVE_AURORA_BEAM,
    MOVE_OCTAZOOKA,
    MOVE_SUPERSONIC,
    MOVE_HAZE,
    MOVE_SCREECH,
    MOVE_THUNDER_WAVE,
    MOVE_ROCK_BLAST,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DELIBIRD
static const u16 sDelibirdEggMoveLearnset_KismetGen3[] = {
    MOVE_AURORA_BEAM,
    MOVE_QUICK_ATTACK,
    MOVE_FUTURE_SIGHT,
    MOVE_EXTRASENSORY,
    MOVE_SPLASH,
    MOVE_RAPID_SPIN,
    MOVE_ICE_BALL,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MANTINE
static const u16 sMantineEggMoveLearnset_KismetGen3[] = {
    MOVE_TWISTER,
    MOVE_HYDRO_PUMP,
    MOVE_HAZE,
    MOVE_SLAM,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKARMORY
static const u16 sSkarmoryEggMoveLearnset_KismetGen3[] = {
    MOVE_DRILL_PECK,
    MOVE_PURSUIT,
    MOVE_WHIRLWIND,
    MOVE_SKY_ATTACK,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_HOUNDOUR
static const u16 sHoundourEggMoveLearnset_KismetGen3[] = {
    MOVE_FIRE_SPIN,
    MOVE_RAGE,
    MOVE_PURSUIT,
    MOVE_COUNTER,
    MOVE_SPITE,
    MOVE_REVERSAL,
    MOVE_SHADOW_SNEAK,
    MOVE_BEAT_UP,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PHANPY
static const u16 sPhanpyEggMoveLearnset_KismetGen3[] = {
    MOVE_FOCUS_ENERGY,
    MOVE_BODY_SLAM,
    MOVE_ANCIENT_POWER,
    MOVE_SNORE,
    MOVE_COUNTER,
    MOVE_FISSURE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_STANTLER
static const u16 sStantlerEggMoveLearnset_KismetGen3[] = {
    MOVE_SPITE,
    MOVE_DISABLE,
    MOVE_BITE,
    MOVE_SWAGGER,
    MOVE_PSYCH_UP,
    MOVE_EXTRASENSORY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MILTANK
static const u16 sMiltankEggMoveLearnset_KismetGen3[] = {
    MOVE_PRESENT,
    MOVE_REVERSAL,
    MOVE_SEISMIC_TOSS,
    MOVE_ENDURE,
    MOVE_PSYCH_UP,
    MOVE_CURSE,
    MOVE_HELPING_HAND,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LARVITAR
static const u16 sLarvitarEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_STOMP,
    MOVE_OUTRAGE,
    MOVE_FOCUS_ENERGY,
    MOVE_ANCIENT_POWER,
    MOVE_DARK_PULSE,
    MOVE_DRAGON_DANCE,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TREECKO
static const u16 sTreeckoEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_MUD_SPORT,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_DRAGON_BREATH,
    MOVE_SHADOW_SNEAK,
    MOVE_CRUSH_CLAW,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TORCHIC
static const u16 sTorchicEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_REVERSAL,
    MOVE_ENDURE,
    MOVE_SWAGGER,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MUDKIP
static const u16 sMudkipEggMoveLearnset_KismetGen3[] = {
    MOVE_REFRESH,
    MOVE_UPROAR,
    MOVE_CURSE,
    MOVE_STOMP,
    MOVE_ICE_BALL,
    MOVE_MIRROR_COAT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_POOCHYENA
static const u16 sPoochyenaEggMoveLearnset_KismetGen3[] = {
    MOVE_ASTONISH,
    MOVE_POISON_FANG,
    MOVE_SHADOW_SNEAK,
    MOVE_COVET,
    MOVE_LEER,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ZIGZAGOON
static const u16 sZigzagoonEggMoveLearnset_KismetGen3[] = {
    MOVE_CHARM,
    MOVE_PURSUIT,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LOTAD
static const u16 sLotadEggMoveLearnset_KismetGen3[] = {
    MOVE_SYNTHESIS,
    MOVE_RAZOR_LEAF,
    MOVE_SWEET_SCENT,
    MOVE_LEECH_SEED,
    MOVE_FLAIL,
    MOVE_WATER_GUN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEEDOT
static const u16 sSeedotEggMoveLearnset_KismetGen3[] = {
    MOVE_LEECH_SEED,
    MOVE_AMNESIA,
    MOVE_QUICK_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_TAKE_DOWN,
    MOVE_FALSE_SWIPE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RALTS
static const u16 sRaltsEggMoveLearnset_KismetGen3[] = {
    MOVE_DISABLE,
    MOVE_WILL_O_WISP,
    MOVE_MEAN_LOOK,
    MOVE_HYPNOSIS,
    MOVE_PLAY_ROUGH,
    MOVE_MEMENTO,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SURSKIT
static const u16 sSurskitEggMoveLearnset_KismetGen3[] = {
    MOVE_FORESIGHT,
    MOVE_MUD_SHOT,
    MOVE_PSYBEAM,
    MOVE_HYDRO_PUMP,
    MOVE_MIND_READER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHROOMISH
static const u16 sShroomishEggMoveLearnset_KismetGen3[] = {
    MOVE_FAKE_TEARS,
    MOVE_SWAGGER,
    MOVE_CHARM,
    MOVE_FALSE_SWIPE,
    MOVE_HELPING_HAND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SLAKOTH
static const u16 sSlakothEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_BODY_SLAM,
    MOVE_SNORE,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NINCADA
static const u16 sNincadaEggMoveLearnset_KismetGen3[] = {
    MOVE_ENDURE,
    MOVE_FAINT_ATTACK,
    MOVE_MUD_SLAP,
    MOVE_GUST,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MAKUHITA
static const u16 sMakuhitaEggMoveLearnset_KismetGen3[] = {
    MOVE_FAINT_ATTACK,
    MOVE_DETECT,
    MOVE_FORESIGHT,
    MOVE_HELPING_HAND,
    MOVE_CROSS_CHOP,
    MOVE_REVENGE,
    MOVE_DYNAMIC_PUNCH,
    MOVE_COUNTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NOSEPASS
static const u16 sNosepassEggMoveLearnset_KismetGen3[] = {
    MOVE_MAGNITUDE,
    MOVE_ROLLOUT,
    MOVE_EXPLOSION,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKITTY
static const u16 sSkittyEggMoveLearnset_KismetGen3[] = {
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_UPROAR,
    MOVE_FAKE_TEARS,
    MOVE_WISH,
    MOVE_BATON_PASS,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ARON
static const u16 sAronEggMoveLearnset_KismetGen3[] = {
    MOVE_ENDEAVOR,
    MOVE_BODY_SLAM,
    MOVE_STOMP,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MEDITITE
static const u16 sMedititeEggMoveLearnset_KismetGen3[] = {
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_FORESIGHT,
    MOVE_FAKE_OUT,
    MOVE_BATON_PASS,
    MOVE_DYNAMIC_PUNCH,
    MOVE_PSYCHO_CUT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ELECTRIKE
static const u16 sElectrikeEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_HEADBUTT,
    MOVE_UPROAR,
    MOVE_CURSE,
    MOVE_SWIFT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CARVANHA
static const u16 sCarvanhaEggMoveLearnset_KismetGen3[] = {
    MOVE_HYDRO_PUMP,
    MOVE_DOUBLE_EDGE,
    MOVE_SKULL_BASH,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WAILMER
static const u16 sWailmerEggMoveLearnset_KismetGen3[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_THRASH,
    MOVE_SWAGGER,
    MOVE_SNORE,
    MOVE_SLEEP_TALK,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_NUMEL
static const u16 sNumelEggMoveLearnset_KismetGen3[] = {
    MOVE_HOWL,
    MOVE_SCARY_FACE,
    MOVE_BODY_SLAM,
    MOVE_ROLLOUT,
    MOVE_DEFENSE_CURL,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TORKOAL
static const u16 sTorkoalEggMoveLearnset_KismetGen3[] = {
    MOVE_ERUPTION,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_SLEEP_TALK,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPINDA
static const u16 sSpindaEggMoveLearnset_KismetGen3[] = {
    MOVE_ENCORE,
    MOVE_ROCK_SLIDE,
    MOVE_ASSIST,
    MOVE_DISABLE,
    MOVE_BATON_PASS,
    MOVE_WISH,
    MOVE_TRICK,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SWABLU
static const u16 sSwabluEggMoveLearnset_KismetGen3[] = {
    MOVE_AGILITY,
    MOVE_HAZE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ZANGOOSE
static const u16 sZangooseEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUSH_CLAW,
    MOVE_COUNTER,
    MOVE_FAINT_ATTACK,
    MOVE_REVERSAL,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SEVIPER
static const u16 sSeviperEggMoveLearnset_KismetGen3[] = {
    MOVE_CRUNCH,
    MOVE_GLARE,
    MOVE_POISON_TAIL,
    MOVE_ACID,
    MOVE_BITE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BARBOACH
static const u16 sBarboachEggMoveLearnset_KismetGen3[] = {
    MOVE_THRASH,
    MOVE_WHIRLPOOL,
    MOVE_SPARK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CORPHISH
static const u16 sCorphishEggMoveLearnset_KismetGen3[] = {
    MOVE_MUD_SPORT,
    MOVE_ENDEAVOR,
    MOVE_FALSE_SWIPE,
    MOVE_CROSS_POISON,
    MOVE_REVENGE,
    MOVE_BODY_SLAM,
    MOVE_ANCIENT_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LILEEP
static const u16 sLileepEggMoveLearnset_KismetGen3[] = {
    MOVE_BARRIER,
    MOVE_RECOVER,
    MOVE_MIRROR_COAT,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ANORITH
static const u16 sAnorithEggMoveLearnset_KismetGen3[] = {
    MOVE_RAPID_SPIN,
    MOVE_KNOCK_OFF,
    MOVE_SWORDS_DANCE,
    MOVE_FALSE_SWIPE,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FEEBAS
static const u16 sFeebasEggMoveLearnset_KismetGen3[] = {
    MOVE_MIRROR_COAT,
    MOVE_DRAGON_BREATH,
    MOVE_MUD_SPORT,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CASTFORM
static const u16 sCastformNormalEggMoveLearnset_KismetGen3[] = {
    MOVE_FUTURE_SIGHT,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SHUPPET
static const u16 sShuppetEggMoveLearnset_KismetGen3[] = {
    MOVE_DISABLE,
    MOVE_DESTINY_BOND,
    MOVE_FORESIGHT,
    MOVE_ASTONISH,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DUSKULL
static const u16 sDuskullEggMoveLearnset_KismetGen3[] = {
    MOVE_IMPRISON,
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_GRUDGE,
    MOVE_ASTONISH,
    MOVE_MEMENTO,
    MOVE_FAINT_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TROPIUS
static const u16 sTropiusEggMoveLearnset_KismetGen3[] = {
    MOVE_HEADBUTT,
    MOVE_SLAM,
    MOVE_RAZOR_WIND,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHIMECHO
static const u16 sChimechoEggMoveLearnset_KismetGen3[] = {
    MOVE_DISABLE,
    MOVE_CURSE,
    MOVE_BOOMBURST,
    MOVE_HYPNOSIS,
    MOVE_DREAM_EATER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_ABSOL
static const u16 sAbsolEggMoveLearnset_KismetGen3[] = {
    MOVE_BATON_PASS,
    MOVE_FAINT_ATTACK,
    MOVE_DOUBLE_EDGE,
    MOVE_MAGIC_COAT,
    MOVE_SHADOW_SNEAK,
    MOVE_CURSE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SNORUNT
static const u16 sSnoruntEggMoveLearnset_KismetGen3[] = {
    MOVE_BLOCK,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CLAMPERL
static const u16 sClamperlEggMoveLearnset_KismetGen3[] = {
    MOVE_REFRESH,
    MOVE_MUD_SPORT,
    MOVE_BODY_SLAM,
    MOVE_SUPERSONIC,
    MOVE_BARRIER,
    MOVE_CONFUSE_RAY,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RELICANTH
static const u16 sRelicanthEggMoveLearnset_KismetGen3[] = {
    MOVE_MAGNITUDE,
    MOVE_SKULL_BASH,
    MOVE_WATER_SPORT,
    MOVE_AMNESIA,
    MOVE_SLEEP_TALK,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LUVDISC
static const u16 sLuvdiscEggMoveLearnset_KismetGen3[] = {
    MOVE_SPLASH,
    MOVE_SUPERSONIC,
    MOVE_WATER_SPORT,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TURTWIG
static const u16 sTurtwigEggMoveLearnset_KismetGen3[] = {
    MOVE_LIGHT_SCREEN,
    MOVE_INGRAIN,
    MOVE_SKULL_BASH,
    MOVE_SAFEGUARD,
    MOVE_CHARM,
    MOVE_PETAL_DANCE,
    MOVE_SLUDGE,
    MOVE_NATURE_POWER,
    MOVE_MAGICAL_LEAF,
    MOVE_GRASS_WHISTLE,
    MOVE_EARTH_POWER,
    MOVE_WEATHER_BALL,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_CHIMCHAR
static const u16 sChimcharEggMoveLearnset_KismetGen3[] = {
    MOVE_BELLY_DRUM,
    MOVE_DRAGON_PULSE,
    MOVE_ANCIENT_POWER,
    MOVE_ROCK_SLIDE,
    MOVE_BITE,
    MOVE_OUTRAGE,
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_METAL_CLAW,
    MOVE_BEAT_UP,
    MOVE_SWORDS_DANCE,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_PIPLUP
static const u16 sPiplupEggMoveLearnset_KismetGen3[] = {
    MOVE_MIRROR_COAT,
    MOVE_DRAGON_PULSE,
    MOVE_DARK_PULSE,
    MOVE_FAKE_OUT,
    MOVE_MUDDY_WATER,
    MOVE_HAZE,
    MOVE_MIST,
    MOVE_FORESIGHT,
    MOVE_FLAIL,
    MOVE_REFRESH,
    MOVE_MUD_SPORT,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BRONZOR
static const u16 sBronzorEggMoveLearnset_KismetGen3[] = {
    MOVE_GRASS_WHISTLE,
    MOVE_ACID,
    MOVE_TEETER_DANCE,
    MOVE_DYNAMIC_PUNCH,
    MOVE_COUNTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SPIRITOMB
static const u16 sSpiritombEggMoveLearnset_KismetGen3[] = {
    MOVE_CURSE,
    MOVE_PURSUIT,
    MOVE_PAIN_SPLIT,
    MOVE_NIGHT_SHADE,
    MOVE_DISABLE,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GIBLE
static const u16 sGibleEggMoveLearnset_KismetGen3[] = {
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_DRAGON_RAGE,
    MOVE_TWISTER,
    MOVE_DRAGON_DANCE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RIOLU
static const u16 sRioluEggMoveLearnset_KismetGen3[] = {
    MOVE_BLAZE_KICK,
    MOVE_CRUNCH,
    MOVE_CROSS_CHOP,
    MOVE_MUD_SLAP,
    MOVE_AGILITY,
    MOVE_MIND_READER,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_SKORUPI
static const u16 sSkorupiEggMoveLearnset_KismetGen3[] = {
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_BODY_SLAM,
    MOVE_RAZOR_WIND,
    MOVE_FLAIL,
    MOVE_POISON_TAIL,
    MOVE_GUNK_SHOT,
    MOVE_COUNTER,
    MOVE_ROAR,
    MOVE_CURSE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VANILLITE
static const u16 sVanilliteEggMoveLearnset_KismetGen3[] = {
    MOVE_ENCORE,
    MOVE_BODY_SLAM,
    MOVE_FUTURE_SIGHT,
    MOVE_AMNESIA,
    MOVE_MIRROR_COAT,
    MOVE_EXTRASENSORY,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TYNAMO
static const u16 sTynamoEggMoveLearnset_KismetGen3[] = {
    MOVE_WATER_SPORT,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_SPIT_UP,
    MOVE_YAWN,
    MOVE_ROCK_SLIDE,
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_AXEW
static const u16 sAxewEggMoveLearnset_KismetGen3[] = {
    MOVE_TAKE_DOWN,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_LUNGE,
    MOVE_MUD_SHOT,
    MOVE_DIG,
    MOVE_PLAY_ROUGH,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MIENFOO
static const u16 sMienfooEggMoveLearnset_KismetGen3[] = {
    MOVE_COUNTER,
    MOVE_FOCUS_PUNCH,
    MOVE_MEDITATE,
    MOVE_BLAZE_KICK,
    MOVE_REVENGE,
    MOVE_MIND_READER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_RUFFLET
static const u16 sRuffletEggMoveLearnset_KismetGen3[] = {
    MOVE_MIST,
    MOVE_TWISTER,
    MOVE_AGILITY,
    MOVE_GUST,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_VULLABY
static const u16 sVullabyEggMoveLearnset_KismetGen3[] = {
    MOVE_FEATHER_DANCE,
    MOVE_PURSUIT,
    MOVE_SKY_ATTACK,
    MOVE_COUNTER,
    MOVE_REVENGE,
    MOVE_CURSE,
    MOVE_ENDEAVOR,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_DEINO
static const u16 sDeinoEggMoveLearnset_KismetGen3[] = {
    MOVE_ASTONISH,
    MOVE_EARTH_POWER,
    MOVE_HEAD_SMASH,
    MOVE_SCREECH,
    MOVE_COVET,
    MOVE_FAKE_OUT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_LARVESTA
static const u16 sLarvestaEggMoveLearnset_KismetGen3[] = {
    MOVE_FLAMETHROWER,
    MOVE_MIRROR_COAT,
    MOVE_SPLASH,
    MOVE_ANCIENT_POWER,
    MOVE_MAGIC_COAT,
    MOVE_SCORCHING_SANDS,
    MOVE_GIGA_DRAIN,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FLETCHLING
static const u16 sFletchlingEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_UPROAR,
    MOVE_FLAMETHROWER,
    MOVE_FORESIGHT,
    MOVE_RAZOR_WIND,
    MOVE_STEEL_WING,
    MOVE_AIR_SLASH,
    MOVE_AIR_CUTTER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_FOMANTIS
static const u16 sFomantisEggMoveLearnset_KismetGen3[] = {
    MOVE_SOLAR_BEAM,
    MOVE_LEAF_BLADE,
    MOVE_SWEET_SCENT,
    MOVE_GRASS_WHISTLE,
    MOVE_SYNTHESIS,
    MOVE_AROMATHERAPY,
    MOVE_ENERGY_BALL,
    MOVE_MAGICAL_LEAF,
    MOVE_DOUBLE_EDGE,
    MOVE_NATURE_POWER,
    MOVE_GRASS_KNOT,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_MIMIKYU
static const u16 sMimikyuDisguisedEggMoveLearnset_KismetGen3[] = {
    MOVE_CHARM,
    MOVE_CONFUSE_RAY,
    MOVE_MIMIC,
    MOVE_PSYCH_UP,
    MOVE_FAKE_OUT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_IMPIDIMP
static const u16 sImpidimpEggMoveLearnset_KismetGen3[] = {
    MOVE_TORMENT,
    MOVE_PURSUIT,
    MOVE_SHADOW_SNEAK,
    MOVE_MUD_SLAP,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_WATTREL
static const u16 sWattrelEggMoveLearnset_KismetGen3[] = {
    MOVE_PURSUIT,
    MOVE_SUPERSONIC,
    MOVE_REFRESH,
    MOVE_MIRROR_MOVE,
    MOVE_RAGE,
    MOVE_SKY_ATTACK,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_TINKATINK
static const u16 sTinkatinkEggMoveLearnset_KismetGen3[] = {
    MOVE_DEFENSE_CURL,
    MOVE_IRON_DEFENSE,
    MOVE_TAUNT,
    MOVE_HEADBUTT,
    MOVE_ROLLOUT,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_BOMBIRDIER
static const u16 sBombirdierEggMoveLearnset_KismetGen3[] = {
    MOVE_PRESENT,
    MOVE_WHIRLWIND,
    MOVE_DRILL_PECK,
    MOVE_MIRROR_MOVE,
    MOVE_PAY_DAY,
    MOVE_HAZE,
    MOVE_STONE_EDGE,
    MOVE_SKY_ATTACK,
    MOVE_SCARY_FACE,
    MOVE_NIGHT_SLASH,
    MOVE_PERISH_SONG,
    MOVE_UNAVAILABLE,
};

#endif
#if P_FAMILY_GREAVARD
static const u16 sGreavardEggMoveLearnset_KismetGen3[] = {
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_SAFEGUARD,
    MOVE_DOUBLE_EDGE,
    MOVE_THRASH,
    MOVE_NIGHT_SHADE,
    MOVE_HOWL,
    MOVE_DESTINY_BOND,
    MOVE_UNAVAILABLE,
};

#endif
#if P_KISMET_FAKEMON
static const u16 sKrolucadaEggMoveLearnset_KismetGen3[] = {
    MOVE_BATON_PASS,
    MOVE_SILVER_WIND,
    MOVE_SHADOW_SNEAK,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sLarvicidEggMoveLearnset_KismetGen3[] = {
    MOVE_POUNCE,
    MOVE_ACID_ARMOR,
    MOVE_SMOG,
    MOVE_HEAVY_SLAM,
    MOVE_MIRROR_SHOT,
    MOVE_LUNGE,
    MOVE_UNAVAILABLE,
};

static const u16 sPurgislugEggMoveLearnset_KismetGen3[] = {
    MOVE_PAIN_SPLIT,
    MOVE_EXTRASENSORY,
    MOVE_MIND_READER,
    MOVE_MAGICAL_LEAF,
    MOVE_GRUDGE,
    MOVE_MEMENTO,
    MOVE_UNAVAILABLE,
};

static const u16 sRaelicEggMoveLearnset_KismetGen3[] = {
    MOVE_MIND_READER,
    MOVE_MUD_SHOT,
    MOVE_FLAIL,
    MOVE_EARTH_POWER,
    MOVE_GIGA_DRAIN,
    MOVE_REST,
    MOVE_OUTRAGE,
    MOVE_UNAVAILABLE,
};

#endif
