// Generated by .claude/gen_kismet_species.py - do not edit by hand.
// Kismet's base stats, from the fork's own `_old`-annotated edits. Consulted only when the STATS option is KISMET; species_info.h keeps 2.0's values as the fallback.

static const struct KismetBaseStats sKismetBaseStats[] =
{
    { SPECIES_ABSOL,                         {  65, 130,  60,  90,  90,  60 } }, // Speed SpAttack
    { SPECIES_AGGRON,                        {  70,  95, 120,  45, 115,  85 } }, // Attack Defense Speed SpAttack SpDefense
    { SPECIES_AIPOM,                         {  55,  90,  67, 111,  40,  67 } }, // Attack Defense Speed SpDefense
    { SPECIES_ARBOK,                         {  82,  95,  69,  80,  85,  79 } }, // HP SpAttack
    { SPECIES_ARIADOS,                       {  70,  90,  70,  80,  70,  70 } }, // Speed SpAttack
    { SPECIES_BANETTE,                       {  64, 115,  65,  75,  93,  63 } }, // Speed SpAttack
    { SPECIES_BEEDRILL,                      {  65,  90,  40,  80,  45,  80 } }, // Speed
    { SPECIES_BELLOSSOM,                     {  60,  60,  85,  90, 115, 100 } }, // HP Attack Speed SpAttack
    { SPECIES_BLAZIKEN,                      {  80, 122,  70,  86, 112,  70 } }, // Attack Speed SpAttack
    { SPECIES_BUTTERFREE,                    {  60,  45,  50,  75,  90,  80 } }, // Speed
    { SPECIES_CACTURNE,                      {  90, 115,  90,  35, 115,  60 } }, // HP Defense Speed
    { SPECIES_CAMERUPT,                      {  95, 100,  70,  40, 105,  75 } }, // HP
    { SPECIES_CHARIZARD,                     {  79,  84,  78, 100, 109,  85 } }, // HP
    { SPECIES_CLOYSTER,                      {  50,  95, 180,  70,  45,  85 } }, // SpAttack
    { SPECIES_DELCATTY,                      {  80,  75,  75, 100,  80,  70 } }, // HP Attack Defense SpAttack SpDefense
    { SPECIES_DELIBIRD,                      {  45,  65,  45, 105,  95,  45 } }, // Attack Speed SpAttack
    { SPECIES_DODRIO,                        {  60, 115,  70, 115,  60,  60 } }, // Attack
    { SPECIES_DUSCLOPS,                      {  40,  70, 130,  25,  90, 130 } }, // SpAttack
    { SPECIES_EMPOLEON,                      {  89,  86,  88,  60, 111, 101 } }, // HP
    { SPECIES_EXPLOUD,                       { 114,  96,  73,  68,  96,  73 } }, // HP Attack Defense SpAttack
    { SPECIES_FERALIGATR,                    {  85, 110, 100,  78,  79,  83 } }, // Attack
    { SPECIES_FLAREON,                       {  95,  65,  65,  60, 110, 130 } }, // HP Attack Defense Speed SpDefense
    { SPECIES_GIRAFARIG,                     {  70,  85,  65,  90,  95,  65 } }, // Attack Speed SpAttack
    { SPECIES_GRUMPIG,                       {  95,  45,  65,  80,  90, 110 } }, // HP
    { SPECIES_HITMONCHAN,                    {  40,  75,  89,  76,  75, 110 } }, // HP Attack Defense SpAttack
    { SPECIES_HITMONLEE,                     {  50, 130,  53,  87,  35, 110 } }, // Attack
    { SPECIES_HITMONTOP,                     {  60,  95,  95,  70,  35, 110 } }, // HP
    { SPECIES_HOUNDSTONE,                    {  72, 101, 100,  80,  50,  97 } }, // Speed
    { SPECIES_INFERNAPE,                     {  76, 104,  71, 109, 104,  71 } }, // Speed
    { SPECIES_JUMPLUFF,                      {  75,  55,  80, 110,  55,  95 } }, // Defense
    { SPECIES_KABUTOPS,                      {  60, 120, 105,  90,  65,  70 } }, // Attack Speed
    { SPECIES_KINGDRA,                       {  85,  95,  95,  85,  95,  95 } }, // HP
    { SPECIES_KINGLER,                       {  80, 130, 115,  75,  50,  50 } }, // HP
    { SPECIES_LAIRON,                        {  60,  90, 110,  40,  50,  65 } }, // Defense SpDefense
    { SPECIES_LEAFEON,                       {  65, 130, 110,  95,  60,  65 } }, // Attack Defense
    { SPECIES_LEDIAN,                        {  55,  75,  50,  85,  75, 110 } }, // Attack SpAttack
    { SPECIES_LICKITUNG,                     { 105,  55,  75,  30,  90,  85 } }, // HP SpAttack
    { SPECIES_LUVDISC,                       {  43,  30,  55, 123,  40,  75 } }, // Speed SpDefense
    { SPECIES_MACHAMP,                       { 100, 145,  80,  55,  65,  85 } }, // HP Attack
    { SPECIES_MAGCARGO,                      {  60,  60, 140,  30,  90, 100 } }, // Attack Defense SpDefense
    { SPECIES_MANECTRIC,                     {  70,  85,  60, 105, 105,  60 } }, // Attack
    { SPECIES_MEGANIUM,                      {  80,  82, 105,  80,  83, 105 } }, // Defense SpDefense
    { SPECIES_NIDOQUEEN,                     {  90,  82,  87,  76,  85,  85 } }, // SpAttack
    { SPECIES_NINETALES,                     {  73,  62,  75, 100,  95, 100 } }, // Attack
    { SPECIES_NOCTOWL,                       { 100,  50,  50,  70, 100, 100 } }, // SpDefense
    { SPECIES_NOSEPASS,                      {  50,  45, 135,  30,  75, 110 } }, // HP SpAttack SpDefense
    { SPECIES_OMASTAR,                       {  75,  60, 125,  55, 125,  70 } }, // HP SpAttack
    { SPECIES_PARASECT,                      {  90,  95, 130,  30,  60, 110 } }, // HP Defense SpDefense
    { SPECIES_PERSIAN,                       {  65,  95,  60, 115,  80,  65 } }, // Attack SpAttack
    { SPECIES_PIDGEOT,                       {  90,  80,  80,  91,  80,  70 } }, // HP Defense SpAttack
    { SPECIES_PILOSWINE,                     { 130, 120,  80,  50,  80,  60 } }, // HP Attack SpAttack
    { SPECIES_POLITOED,                      {  90,  75,  75,  85,  90, 100 } }, // Speed
    { SPECIES_PORYGON_Z,                     {  85,  80,  70,  90, 145,  75 } }, // SpAttack
    { SPECIES_PRIMEAPE,                      {  65, 105,  60, 105,  60,  70 } }, // Speed
    { SPECIES_RAICHU,                        {  70,  90,  55, 110,  90,  80 } }, // HP
    { SPECIES_RHYDON,                        { 115, 140, 140,  40,  45,  65 } }, // HP Attack Defense SpDefense
    { SPECIES_SANDSLASH,                     {  75, 100, 110,  85,  45,  65 } }, // Speed SpDefense
    { SPECIES_SCEPTILE,                      {  70,  90,  65, 120, 105,  85 } }, // Attack
    { SPECIES_SHARPEDO,                      {  70, 120,  40, 110,  95,  40 } }, // Speed
    { SPECIES_SHIFTRY,                       {  90, 100,  60,  90,  90,  60 } }, // Speed
    { SPECIES_SKITTY,                        {  50,  45,  45,  70,  35,  35 } }, // Speed
    { SPECIES_SLOWKING,                      {  95,  65,  80,  30, 110, 110 } }, // Attack SpAttack
    { SPECIES_SLUGMA,                        {  40,  40,  50,  20,  70,  50 } }, // Defense SpDefense
    { SPECIES_STEELIX,                       {  75, 100, 200,  30,  55,  65 } }, // Attack
    { SPECIES_SUDOWOODO,                     {  70, 100, 100,  70,  30,  80 } }, // Defense Speed SpDefense
    { SPECIES_SUNFLORA,                      {  75,  55,  55,  75, 115, 115 } }, // Attack Speed SpAttack SpDefense
    { SPECIES_TAUROS,                        {  75, 110,  95, 110,  40,  70 } }, // Attack
    { SPECIES_TOGETIC,                       {  55,  40, 105,  75, 120, 125 } }, // Defense Speed SpAttack SpDefense
    { SPECIES_TORTERRA,                      { 105, 109, 105,  56,  75,  85 } }, // HP
    { SPECIES_TROPIUS,                       { 110,  68,  83,  51,  72,  87 } }, // HP
    { SPECIES_TYPHLOSION,                    {  78,  84,  78, 101, 109,  85 } }, // Speed
    { SPECIES_VENOMOTH,                      {  70,  75,  60, 105,  95,  80 } }, // Attack Speed SpAttack
    { SPECIES_VENUSAUR,                      {  80,  87,  83,  80, 105, 100 } }, // Attack SpAttack
    { SPECIES_VICTREEBEL,                    {  80, 115,  65,  70, 100,  70 } }, // Attack
    { SPECIES_VILEPLUME,                     {  85,  80,  85,  50, 115,  90 } }, // HP
    { SPECIES_WAILORD,                       { 200,  90,  45,  60,  90,  45 } }, // HP
    { SPECIES_WIGGLYTUFF,                    { 155,  80,  70,  45,  75,  50 } }, // HP Attack Defense
    { SPECIES_XATU,                          {  70,  75,  80,  97, 113,  80 } }, // HP Defense Speed SpAttack SpDefense
};
